SuperDialogue = {  -- not being used yet
	WifeSpeech = {
		getText("SS_dialogues_WifeSpeech1"),
		getText("SS_dialogues_WifeSpeech2"),
		getText("SS_dialogues_WifeSpeech3"),
		getText("SS_dialogues_WifeSpeech4"),
		getText("SS_dialogues_WifeSpeech5"),
	}
}

if not SurvivorSpeechTable then 
  SurvivorSpeechTable = {} 
end

SurvivorSpeechTable["HelloThere"] = {
  getText("SS_dialogues_HiThere"),
  getText("SS_dialogues_HelloThere"),
  getText("SS_dialogues_HelloWord1"),
	getText("SS_dialogues_HelloWord2"),
	getText("SS_dialogues_HelloWord3"),
	getText("SS_dialogues_HelloWord4"),
	getText("SS_dialogues_HelloWord5"),
	getText("SS_dialogues_HelloWord6"),
	getText("SS_dialogues_HelloWord7"),
	getText("SS_dialogues_HelloWord8"),
	getText("SS_dialogues_HelloWord9"),
	getText("SS_dialogues_HelloWord10"),
	getText("SS_dialogues_HelloWord11"),
	getText("SS_dialogues_HelloWord12"),
	getText("SS_dialogues_HelloWord13"),
	getText("SS_dialogues_HelloWord14"),
};
	
SurvivorSpeechTable["OutOfAmmo"] = {
  getText("SS_dialogues_OutOfAmmo1"),
  getText("SS_dialogues_OutOfAmmo2"),
  getText("SS_dialogues_OutOfAmmo3"),
	getText("SS_dialogues_OutOfAmmo4"),
};
	
SurvivorSpeechTable["HowDareYou"] = {
  getText("SS_dialogues_HowDareYou1"),
};		
SurvivorSpeechTable["WifeIntro"] = {
  getText("SS_dialogues_WifeIntro1"),
};	
	
SurvivorSpeechTable["IDontKnowHowDoctor"] = {
  getText("SS_dialogues_IDontKnowHowDoctor1"),
};

SurvivorSpeechTable["IfYouThinkSo"] = {
  getText("SS_dialogues_IfYouThinkSo1"),
  getText("SS_dialogues_IfYouThinkSo2"),
};
     
SurvivorSpeechTable["SawHimThere"] = {
  getText("SS_dialogues_SawHimThere1"),
  getText("SS_dialogues_SawHimThere2"),
  getText("SS_dialogues_SawHimThere3"),
	getText("SS_dialogues_SawHimThere4"),
};
	
SurvivorSpeechTable["GonnaGetYou"] = {
  getText("SS_dialogues_GonnaGetYou1"),
  getText("SS_dialogues_GonnaGetYou2"),
  getText("SS_dialogues_GonnaGetYou3"),
  getText("SS_dialogues_GonnaGetYou4"),
  getText("SS_dialogues_GonnaGetYou5"),
};
     
  
SurvivorSpeechTable["SeenPlayerIll"] = {
  getText("SS_dialogues_SeenPlayerIll1"),
  getText("SS_dialogues_SeenPlayerIll2"),
  getText("SS_dialogues_SeenPlayerIll3"),
  getText("SS_dialogues_SeenPlayerIll4"),
  getText("SS_dialogues_SeenPlayerIll5"),
  getText("SS_dialogues_SeenPlayerIll6"),
  getText("SS_dialogues_SeenPlayerIll7"),
  getText("SS_dialogues_SeenPlayerIll8"),
};
     
SurvivorSpeechTable["SeenPlayerBit"] = {
  getText("SS_dialogues_SeenPlayerBit1"),
  getText("SS_dialogues_SeenPlayerBit2"),
  getText("SS_dialogues_SeenPlayerBit3"),
  getText("SS_dialogues_SeenPlayerBit4"),
  getText("SS_dialogues_SeenPlayerBit5"),
  getText("SS_dialogues_SeenPlayerBit6"),
  getText("SS_dialogues_SeenPlayerBit7"),
  getText("SS_dialogues_SeenPlayerBit8"),
  getText("SS_dialogues_SeenPlayerBit9"),
  getText("SS_dialogues_SeenPlayerBit10"),
  getText("SS_dialogues_SeenPlayerBit11"),
  getText("SS_dialogues_SeenPlayerBit12"),
  getText("SS_dialogues_SeenPlayerBit13"),
};
    
SurvivorSpeechTable["Crying"] = {
  getText("SS_dialogues_Crying1"),
  getText("SS_dialogues_Crying2"),
  getText("SS_dialogues_Crying3"),
  getText("SS_dialogues_Crying4"),
  getText("SS_dialogues_Crying5"),
  getText("SS_dialogues_Crying6"),
  getText("SS_dialogues_Crying7"),
  getText("SS_dialogues_Crying8"),
  getText("SS_dialogues_Crying9"),
  getText("SS_dialogues_Crying10"),
  getText("SS_dialogues_Crying11"),
  getText("SS_dialogues_Crying12"),
  getText("SS_dialogues_Crying13"),
  getText("SS_dialogues_Crying14"),
  getText("SS_dialogues_Crying15"),
  getText("SS_dialogues_Crying16"),
};
      
SurvivorSpeechTable["Tired"] = {
	getText("SS_dialogues_Tired1"),
  getText("SS_dialogues_Tired2"),
  getText("SS_dialogues_Tired3"),
  getText("SS_dialogues_Tired4"),
  getText("SS_dialogues_Tired5"),
  getText("SS_dialogues_Tired6"),
  getText("SS_dialogues_Tired7"),
  getText("SS_dialogues_Tired8"),
  getText("SS_dialogues_Tired9"),
  getText("SS_dialogues_Tired10"),
  getText("SS_dialogues_Tired11"),
};
 

SurvivorSpeechTable["VTired"] = {
  getText("SS_dialogues_VTired1"),
  getText("SS_dialogues_VTired2"),
  getText("SS_dialogues_VTired3"),
  getText("SS_dialogues_VTired4"),
  getText("SS_dialogues_VTired5"),
  getText("SS_dialogues_VTired6"),
};
 

 
SurvivorSpeechTable["STired"] = {
  getText("SS_dialogues_STired1"),
  getText("SS_dialogues_STired2"),
  getText("SS_dialogues_STired3"),
  getText("SS_dialogues_STired4"),
  getText("SS_dialogues_STired5"),
  getText("SS_dialogues_STired6"),
  getText("SS_dialogues_STired7"),
};

   
SurvivorSpeechTable["Thirsty"] = {
  getText("SS_dialogues_Thirsty1"),
  getText("SS_dialogues_Thirsty2"),
  getText("SS_dialogues_Thirsty3"),
  getText("SS_dialogues_Thirsty4"),
  getText("SS_dialogues_Thirsty5"),
  getText("SS_dialogues_Thirsty6"),
  getText("SS_dialogues_Thirsty7"),
  getText("SS_dialogues_Thirsty8"),
  getText("SS_dialogues_Thirsty9"),
  getText("SS_dialogues_Thirsty10"),
};
 

SurvivorSpeechTable["VThirsty"] = {
  getText("SS_dialogues_VThirsty1"),
  getText("SS_dialogues_VThirsty2"),
  getText("SS_dialogues_VThirsty3"),
  getText("SS_dialogues_VThirsty4"),
  getText("SS_dialogues_VThirsty5"),
  getText("SS_dialogues_VThirsty6"),
  getText("SS_dialogues_VThirsty7"),
  getText("SS_dialogues_VThirsty8"),
  getText("SS_dialogues_VThirsty9"),
  getText("SS_dialogues_VThirsty10"),
};
 

SurvivorSpeechTable["SThirsty"] = {
  getText("SS_dialogues_SThirsty1"),
  getText("SS_dialogues_SThirsty2"),
  getText("SS_dialogues_SThirsty3"),
  getText("SS_dialogues_SThirsty4"),
  getText("SS_dialogues_SThirsty5"),
  getText("SS_dialogues_SThirsty6"),
  getText("SS_dialogues_SThirsty7"),
  getText("SS_dialogues_SThirsty8"),
  getText("SS_dialogues_SThirsty9"),
  getText("SS_dialogues_SThirsty10"),
};

 
SurvivorSpeechTable["Respond"] = {
  getText("SS_dialogues_Respond1"),
  getText("SS_dialogues_Respond2"),
  getText("SS_dialogues_Respond3"),
  getText("SS_dialogues_Respond4"),
  getText("SS_dialogues_Respond5"),
  getText("SS_dialogues_Respond6"),
  getText("SS_dialogues_Respond7"),
  getText("SS_dialogues_Respond8"),
  getText("SS_dialogues_Respond9"),
  getText("SS_dialogues_Respond10"),
  getText("SS_dialogues_Respond11"),
  getText("SS_dialogues_Respond12"),
  getText("SS_dialogues_Respond13"),
  getText("SS_dialogues_Respond14"),
  getText("SS_dialogues_Respond15"),
  getText("SS_dialogues_Respond16"),
  getText("SS_dialogues_Respond17"),
  getText("SS_dialogues_Respond18"),
  getText("SS_dialogues_Respond19"),
  getText("SS_dialogues_Respond20"),
};
 
SurvivorSpeechTable["Sick"] = {
  getText("SS_dialogues_Sick1"),
  getText("SS_dialogues_Sick2"),
};
 
SurvivorSpeechTable["VSick"] = {
  getText("SS_dialogues_VSick1"),
  getText("SS_dialogues_VSick2"),
};
 
SurvivorSpeechTable["SSick"] = {
  getText("SS_dialogues_SSick1"),
  getText("SS_dialogues_SSick2"),
};
 
SurvivorSpeechTable["Hungry"] = {
  getText("SS_dialogues_Hungry1"),
  getText("SS_dialogues_Hungry2"),
  getText("SS_dialogues_Hungry3"),
  getText("SS_dialogues_Hungry4"),
  getText("SS_dialogues_Hungry5"),
  getText("SS_dialogues_Hungry6"),
  getText("SS_dialogues_Hungry7"),
  getText("SS_dialogues_Hungry8"),
  getText("SS_dialogues_Hungry9"),
  getText("SS_dialogues_Hungry10"),
};
 
SurvivorSpeechTable["VHungry"] = {
  getText("SS_dialogues_VHungry1"),
  getText("SS_dialogues_VHungry2"),
  getText("SS_dialogues_VHungry3"),
  getText("SS_dialogues_VHungry4"),
  getText("SS_dialogues_VHungry5"),
  getText("SS_dialogues_VHungry6"),
  getText("SS_dialogues_VHungry7"),
  getText("SS_dialogues_VHungry8"),
  getText("SS_dialogues_VHungry9"),
  getText("SS_dialogues_VHungry10"),
};
 

SurvivorSpeechTable["Starving"] = {
  getText("SS_dialogues_Starving1"),
  getText("SS_dialogues_Starving2"),
  getText("SS_dialogues_Starving3"),
  getText("SS_dialogues_Starving4"),
  getText("SS_dialogues_Starving5"),
  getText("SS_dialogues_Starving6"),
  getText("SS_dialogues_Starving7"),
  getText("SS_dialogues_Starving8"),
  getText("SS_dialogues_Starving9"),
  getText("SS_dialogues_Starving10"),
};

SurvivorSpeechTable["Roger"] = {
  getText("SS_dialogues_Roger1"),
  getText("SS_dialogues_Roger2"),
  getText("SS_dialogues_Roger3"),
  getText("SS_dialogues_Roger4"),
  getText("SS_dialogues_Roger5"),
  getText("SS_dialogues_Roger6"),
  getText("SS_dialogues_Roger7"),
  getText("SS_dialogues_Roger8"),
  getText("SS_dialogues_Roger9"),
  getText("SS_dialogues_Roger10"),
  getText("SS_dialogues_Roger11"),
  getText("SS_dialogues_Roger12"),
  getText("SS_dialogues_Roger13"),
  getText("SS_dialogues_Roger14"),
  getText("SS_dialogues_Roger15"),
  getText("SS_dialogues_Roger16"),
  getText("SS_dialogues_Roger17"),
  getText("SS_dialogues_Roger18"),
  getText("SS_dialogues_Roger19"),
  getText("SS_dialogues_Roger20"),
  getText("SS_dialogues_Roger21"),
  getText("SS_dialogues_Roger22"),
  getText("SS_dialogues_Roger23"),
  getText("SS_dialogues_Roger24"),
  getText("SS_dialogues_Roger25"),
  getText("SS_dialogues_Roger26"),
  getText("SS_dialogues_Roger27"),
  getText("SS_dialogues_Roger28"),
  getText("SS_dialogues_Roger29"),
  getText("SS_dialogues_Roger30"),
};
 
SurvivorSpeechTable["No"] = {
	getText("SS_dialogues_No1"),
  getText("SS_dialogues_No2"),
  getText("SS_dialogues_No3"),
  getText("SS_dialogues_No4"),
  getText("SS_dialogues_No5"),
  getText("SS_dialogues_No6"),
  getText("SS_dialogues_No7"),
  getText("SS_dialogues_No8"),
  getText("SS_dialogues_No9"),
  getText("SS_dialogues_No10"),
  getText("SS_dialogues_No11"),
  getText("SS_dialogues_No12"),
 };
 
SurvivorSpeechTable["Thanks"] = {
 getText("SS_dialogues_Thanks1"),
 getText("SS_dialogues_Thanks2"),
 getText("SS_dialogues_Thanks3"),
 getText("SS_dialogues_Thanks4"),
 getText("SS_dialogues_Thanks5"),
 getText("SS_dialogues_Thanks6"),
 getText("SS_dialogues_Thanks7"),
 getText("SS_dialogues_Thanks8"),
};

SurvivorSpeechTable["HitByPlayer"] = {
  getText("SS_dialogues_HitByPlayer1"),
  getText("SS_dialogues_HitByPlayer2"),
  getText("SS_dialogues_HitByPlayer3"),
  getText("SS_dialogues_HitByPlayer4"),
  getText("SS_dialogues_HitByPlayer5"),
  getText("SS_dialogues_HitByPlayer6"),
  getText("SS_dialogues_HitByPlayer7"),
  getText("SS_dialogues_HitByPlayer8"),
  getText("SS_dialogues_HitByPlayer9"),
  getText("SS_dialogues_HitByPlayer10"),
  getText("SS_dialogues_HitByPlayer11"),
  getText("SS_dialogues_HitByPlayer12"),
  getText("SS_dialogues_HitByPlayer13"),
  getText("SS_dialogues_HitByPlayer14"),
  getText("SS_dialogues_HitByPlayer15"),
  getText("SS_dialogues_HitByPlayer16"),
  getText("SS_dialogues_HitByPlayer17"),
  getText("SS_dialogues_HitByPlayer18"),
  getText("SS_dialogues_HitByPlayer19"),
  getText("SS_dialogues_HitByPlayer20"),
  getText("SS_dialogues_HitByPlayer21"),
  getText("SS_dialogues_HitByPlayer22"),
  getText("SS_dialogues_HitByPlayer23"),
  getText("SS_dialogues_HitByPlayer24"),
  getText("SS_dialogues_HitByPlayer25"),
  getText("SS_dialogues_HitByPlayer26"),
  getText("SS_dialogues_HitByPlayer27"),
  getText("SS_dialogues_HitByPlayer28"),
  getText("SS_dialogues_HitByPlayer29"),
};

 
SurvivorSpeechTable["SeenFirstZombie"] = {
  getText("SS_dialogues_SeenFirstZombie1"),
  getText("SS_dialogues_SeenFirstZombie2"),
  getText("SS_dialogues_SeenFirstZombie3"),
  getText("SS_dialogues_SeenFirstZombie4"),
  getText("SS_dialogues_SeenFirstZombie5"),
  getText("SS_dialogues_SeenFirstZombie6"),
  getText("SS_dialogues_SeenFirstZombie7"),
  getText("SS_dialogues_SeenFirstZombie8"),
  getText("SS_dialogues_SeenFirstZombie9"),
  getText("SS_dialogues_SeenFirstZombie10"),
  getText("SS_dialogues_SeenFirstZombie11"),
  getText("SS_dialogues_SeenFirstZombie12"),
  getText("SS_dialogues_SeenFirstZombie13"),
  getText("SS_dialogues_SeenFirstZombie14"),
  getText("SS_dialogues_SeenFirstZombie15"),
  getText("SS_dialogues_SeenFirstZombie16"),
  getText("SS_dialogues_SeenFirstZombie17"),
  getText("SS_dialogues_SeenFirstZombie18"),
};
 

SurvivorSpeechTable["IdleChatter"] = {
  getText("SS_dialogues_IdleChatter1"),
  getText("SS_dialogues_IdleChatter2"),
  getText("SS_dialogues_IdleChatter3"),
  getText("SS_dialogues_IdleChatter4"),
  getText("SS_dialogues_IdleChatter5"),
  getText("SS_dialogues_IdleChatter6"),
  getText("SS_dialogues_IdleChatter7"),
  getText("SS_dialogues_IdleChatter8"),
  getText("SS_dialogues_IdleChatter9"),
  getText("SS_dialogues_IdleChatter10"),
  getText("SS_dialogues_IdleChatter11"),
  getText("SS_dialogues_IdleChatter12"),
  getText("SS_dialogues_IdleChatter13"),
  getText("SS_dialogues_IdleChatter14"),
  getText("SS_dialogues_IdleChatter15"),
  getText("SS_dialogues_IdleChatter16"),
  getText("SS_dialogues_IdleChatter17"),
  getText("SS_dialogues_IdleChatter18"),
  getText("SS_dialogues_IdleChatter19"),
  getText("SS_dialogues_IdleChatter20"),
  getText("SS_dialogues_IdleChatter21"),
  getText("SS_dialogues_IdleChatter22"),
  getText("SS_dialogues_IdleChatter23"),
  getText("SS_dialogues_IdleChatter24"),
  getText("SS_dialogues_IdleChatter25"),
  getText("SS_dialogues_IdleChatter26"),
  getText("SS_dialogues_IdleChatter27"),
  getText("SS_dialogues_IdleChatter28"),
  getText("SS_dialogues_IdleChatter29"),
  getText("SS_dialogues_IdleChatter30"),
  getText("SS_dialogues_IdleChatter31"),
  getText("SS_dialogues_IdleChatter32"),
  getText("SS_dialogues_IdleChatter33"),
  getText("SS_dialogues_IdleChatter34"),
  getText("SS_dialogues_IdleChatter35"),
  getText("SS_dialogues_IdleChatter36"),
  getText("SS_dialogues_IdleChatter37"),
  getText("SS_dialogues_IdleChatter38"),
  getText("SS_dialogues_IdleChatter39"),
  getText("SS_dialogues_IdleChatter40"),
  getText("SS_dialogues_IdleChatter41"),
  getText("SS_dialogues_IdleChatter42"),
  getText("SS_dialogues_IdleChatter43"),
  getText("SS_dialogues_IdleChatter44"),
  getText("SS_dialogues_IdleChatter45"),
  getText("SS_dialogues_IdleChatter46"),
  getText("SS_dialogues_IdleChatter47"),
  getText("SS_dialogues_IdleChatter48"),
  getText("SS_dialogues_IdleChatter49"),
  getText("SS_dialogues_IdleChatter50"),
  getText("SS_dialogues_IdleChatter51"),
  getText("SS_dialogues_IdleChatter52"),
  getText("SS_dialogues_IdleChatter53"),
  getText("SS_dialogues_IdleChatter54"),
  getText("SS_dialogues_IdleChatter55"),
  getText("SS_dialogues_IdleChatter56"),
  getText("SS_dialogues_IdleChatter57"),
  getText("SS_dialogues_IdleChatter58"),
  getText("SS_dialogues_IdleChatter59"),
  getText("SS_dialogues_IdleChatter60"),
  getText("SS_dialogues_IdleChatter61"),
  getText("SS_dialogues_IdleChatter62"),
  getText("SS_dialogues_IdleChatter63"),
  getText("SS_dialogues_IdleChatter64"),
  getText("SS_dialogues_IdleChatter65"),
  getText("SS_dialogues_IdleChatter66"),
  getText("SS_dialogues_IdleChatter67"),
  getText("SS_dialogues_IdleChatter68"),
  getText("SS_dialogues_IdleChatter69"),
  getText("SS_dialogues_IdleChatter70"),
  getText("SS_dialogues_IdleChatter71"),
  getText("SS_dialogues_IdleChatter72"),
  getText("SS_dialogues_IdleChatter73"),
  getText("SS_dialogues_IdleChatter74"),
  getText("SS_dialogues_IdleChatter75"),
  getText("SS_dialogues_IdleChatter76"),
  getText("SS_dialogues_IdleChatter77"),
  getText("SS_dialogues_IdleChatter78"),
  getText("SS_dialogues_IdleChatter79"),
  getText("SS_dialogues_IdleChatter80"),
  getText("SS_dialogues_IdleChatter81"),
  getText("SS_dialogues_IdleChatter82"),
  getText("SS_dialogues_IdleChatter83"),
  getText("SS_dialogues_IdleChatter84"),
  getText("SS_dialogues_IdleChatter85"),
  getText("SS_dialogues_IdleChatter86"),
  getText("SS_dialogues_IdleChatter87"),
  getText("SS_dialogues_IdleChatter88"),
  getText("SS_dialogues_IdleChatter89"),
  getText("SS_dialogues_IdleChatter90"),
  getText("SS_dialogues_IdleChatter91"),
  getText("SS_dialogues_IdleChatter92"),
  getText("SS_dialogues_IdleChatter93"),
  getText("SS_dialogues_IdleChatter94"),
  getText("SS_dialogues_IdleChatter95"),
  getText("SS_dialogues_IdleChatter96"),
  getText("SS_dialogues_IdleChatter97"),
  getText("SS_dialogues_IdleChatter98"),
  getText("SS_dialogues_IdleChatter99"),
  getText("SS_dialogues_IdleChatter100"),
  getText("SS_dialogues_IdleChatter101"),
  getText("SS_dialogues_IdleChatter102"),
  getText("SS_dialogues_IdleChatter103"),
  getText("SS_dialogues_IdleChatter104"),
  getText("SS_dialogues_IdleChatter105"),
  getText("SS_dialogues_IdleChatter106"),
  getText("SS_dialogues_IdleChatter107"),
  getText("SS_dialogues_IdleChatter108"),
  getText("SS_dialogues_IdleChatter109"),
  getText("SS_dialogues_IdleChatter110"),
  getText("SS_dialogues_IdleChatter111"),
  getText("SS_dialogues_IdleChatter112"),
  getText("SS_dialogues_IdleChatter113"),
  getText("SS_dialogues_IdleChatter114"),
  getText("SS_dialogues_IdleChatter115"),
  getText("SS_dialogues_IdleChatter116"),
  getText("SS_dialogues_IdleChatter117"),
  getText("SS_dialogues_IdleChatter118"),
  getText("SS_dialogues_IdleChatter119"),
  getText("SS_dialogues_IdleChatter120"),
  getText("SS_dialogues_IdleChatter121"),
  getText("SS_dialogues_IdleChatter122"),
  getText("SS_dialogues_IdleChatter123"),
  getText("SS_dialogues_IdleChatter124"),
  getText("SS_dialogues_IdleChatter125"),
  getText("SS_dialogues_IdleChatter126"),
  getText("SS_dialogues_IdleChatter127"),
  getText("SS_dialogues_IdleChatter128"),
  getText("SS_dialogues_IdleChatter129"),
  getText("SS_dialogues_IdleChatter130"),
  getText("SS_dialogues_IdleChatter131"),
  getText("SS_dialogues_IdleChatter132"),
  getText("SS_dialogues_IdleChatter133"),
  getText("SS_dialogues_IdleChatter134"),
  getText("SS_dialogues_IdleChatter135"),
  getText("SS_dialogues_IdleChatter136"),
  getText("SS_dialogues_IdleChatter137"),
  getText("SS_dialogues_IdleChatter138"),
  getText("SS_dialogues_IdleChatter139"),
  getText("SS_dialogues_IdleChatter140"),
};
 

SurvivorSpeechTable["PreZombieChatter"] = {
  getText("SS_dialogues_PreZombieChatter1"),
  getText("SS_dialogues_PreZombieChatter2"),
  getText("SS_dialogues_PreZombieChatter3"),
  getText("SS_dialogues_PreZombieChatter4"),
  getText("SS_dialogues_PreZombieChatter5"),
  getText("SS_dialogues_PreZombieChatter6"),
  getText("SS_dialogues_PreZombieChatter7"),
  getText("SS_dialogues_PreZombieChatter8"),
  getText("SS_dialogues_PreZombieChatter9"),
  getText("SS_dialogues_PreZombieChatter10"),
  getText("SS_dialogues_PreZombieChatter11"),
  getText("SS_dialogues_PreZombieChatter12"),
  getText("SS_dialogues_PreZombieChatter13"),
  getText("SS_dialogues_PreZombieChatter14"),
};
 

SurvivorSpeechTable["Hurt"] = {
  getText("SS_dialogues_Hurt1"),
  getText("SS_dialogues_Hurt2"),
  getText("SS_dialogues_Hurt3"),
  getText("SS_dialogues_Hurt4"),
  getText("SS_dialogues_Hurt5"),
  getText("SS_dialogues_Hurt6"),
  getText("SS_dialogues_Hurt7"),
  getText("SS_dialogues_Hurt8"),
  getText("SS_dialogues_Hurt9"),
  getText("SS_dialogues_Hurt10"),
  getText("SS_dialogues_Hurt11"),
  getText("SS_dialogues_Hurt12"),
  getText("SS_dialogues_Hurt13"),
  getText("SS_dialogues_Hurt14"),
  getText("SS_dialogues_Hurt15"),
  getText("SS_dialogues_Hurt16"),
  getText("SS_dialogues_Hurt17"),
  getText("SS_dialogues_Hurt18"),
};
 

SurvivorSpeechTable["Injured"] = {
  getText("SS_dialogues_Injured1"),
  getText("SS_dialogues_Injured2"),
  getText("SS_dialogues_Injured3"),
  getText("SS_dialogues_Injured4"),
  getText("SS_dialogues_Injured5"),
  getText("SS_dialogues_Injured6"),
  getText("SS_dialogues_Injured7"),
  getText("SS_dialogues_Injured8"),
  getText("SS_dialogues_Injured9"),
  getText("SS_dialogues_Injured10"),
  getText("SS_dialogues_Injured11"),
  getText("SS_dialogues_Injured12"),
  getText("SS_dialogues_Injured13"),
  getText("SS_dialogues_Injured14"),
  getText("SS_dialogues_Injured15"),
  getText("SS_dialogues_Injured16"),
  getText("SS_dialogues_Injured17"),
  getText("SS_dialogues_Injured18"),
  getText("SS_dialogues_Injured19"),
  getText("SS_dialogues_Injured20"),
};
 

 
SurvivorSpeechTable["BadInjured"] = {
  getText("SS_dialogues_BadInjured1"),
  getText("SS_dialogues_BadInjured2"),
  getText("SS_dialogues_BadInjured3"),
  getText("SS_dialogues_BadInjured4"),
  getText("SS_dialogues_BadInjured5"),
  getText("SS_dialogues_BadInjured6"),
  getText("SS_dialogues_BadInjured7"),
  getText("SS_dialogues_BadInjured8"),
  getText("SS_dialogues_BadInjured9"),
  getText("SS_dialogues_BadInjured10"),
  getText("SS_dialogues_BadInjured11"),
  getText("SS_dialogues_BadInjured12"),
  getText("SS_dialogues_BadInjured13"),
  getText("SS_dialogues_BadInjured14"),
  getText("SS_dialogues_BadInjured15"),
  getText("SS_dialogues_BadInjured16"),
  getText("SS_dialogues_BadInjured17"),
};
 

SurvivorSpeechTable["SeriousInjured"] = {
  getText("SS_dialogues_SeriousInjured1"),
  getText("SS_dialogues_SeriousInjured2"),
  getText("SS_dialogues_SeriousInjured3"),
  getText("SS_dialogues_SeriousInjured4"),
  getText("SS_dialogues_SeriousInjured5"),
  getText("SS_dialogues_SeriousInjured6"),
  getText("SS_dialogues_SeriousInjured7"),
  getText("SS_dialogues_SeriousInjured8"),
  getText("SS_dialogues_SeriousInjured9"),
  getText("SS_dialogues_SeriousInjured10"),
  getText("SS_dialogues_SeriousInjured11"),
  getText("SS_dialogues_SeriousInjured12"),
  getText("SS_dialogues_SeriousInjured13"),
  getText("SS_dialogues_SeriousInjured14"),
  getText("SS_dialogues_SeriousInjured15"),
  getText("SS_dialogues_SeriousInjured16"),
  getText("SS_dialogues_SeriousInjured17"),
  getText("SS_dialogues_SeriousInjured18"),
  getText("SS_dialogues_SeriousInjured19"),
  getText("SS_dialogues_SeriousInjured20"),
  getText("SS_dialogues_SeriousInjured21"),
  getText("SS_dialogues_SeriousInjured22"),
  getText("SS_dialogues_SeriousInjured23"),
};
 

SurvivorSpeechTable["FatalInjured"] = {
  getText("SS_dialogues_FatalInjured1"),
  getText("SS_dialogues_FatalInjured2"),
  getText("SS_dialogues_FatalInjured3"),
  getText("SS_dialogues_FatalInjured4"),
  getText("SS_dialogues_FatalInjured5"),
  getText("SS_dialogues_FatalInjured6"),
  getText("SS_dialogues_FatalInjured7"),
  getText("SS_dialogues_FatalInjured8"),
  getText("SS_dialogues_FatalInjured9"),
  getText("SS_dialogues_FatalInjured10"),
  getText("SS_dialogues_FatalInjured11"),
  getText("SS_dialogues_FatalInjured12"),
  getText("SS_dialogues_FatalInjured13"),
  getText("SS_dialogues_FatalInjured14"),
  getText("SS_dialogues_FatalInjured15"),
  getText("SS_dialogues_FatalInjured16"),
  getText("SS_dialogues_FatalInjured17"),
};
 

SurvivorSpeechTable["FinalWords"] = {
  getText("SS_dialogues_FinalWords1"),
  getText("SS_dialogues_FinalWords2"),
  getText("SS_dialogues_FinalWords3"),
  getText("SS_dialogues_FinalWords4"),
  getText("SS_dialogues_FinalWords5"),
  getText("SS_dialogues_FinalWords6"),
  getText("SS_dialogues_FinalWords7"),
  getText("SS_dialogues_FinalWords8"),
  getText("SS_dialogues_FinalWords9"),
  getText("SS_dialogues_FinalWords10"),
  getText("SS_dialogues_FinalWords11"),
  getText("SS_dialogues_FinalWords12"),
  getText("SS_dialogues_FinalWords13"),
  getText("SS_dialogues_FinalWords14"),
  getText("SS_dialogues_FinalWords15"),
  getText("SS_dialogues_FinalWords16"),
  getText("SS_dialogues_FinalWords17"),
  getText("SS_dialogues_FinalWords18"),
  getText("SS_dialogues_FinalWords19"),
  getText("SS_dialogues_FinalWords20"),
  getText("SS_dialogues_FinalWords21"),
  getText("SS_dialogues_FinalWords22"),
  getText("SS_dialogues_FinalWords23"),
  getText("SS_dialogues_FinalWords24"),
  getText("SS_dialogues_FinalWords25"),
  getText("SS_dialogues_FinalWords26"),
  getText("SS_dialogues_FinalWords27"),
  getText("SS_dialogues_FinalWords28"),
  getText("SS_dialogues_FinalWords29"),
  getText("SS_dialogues_FinalWords30"),
  getText("SS_dialogues_FinalWords31"),
};
 

 
SurvivorSpeechTable["NameText"] = {
  getText("SS_dialogues_NameText1"),
  getText("SS_dialogues_NameText2"),
  getText("SS_dialogues_NameText3"),
  getText("SS_dialogues_NameText4"),
  getText("SS_dialogues_NameText5"),
  getText("SS_dialogues_NameText6"),
  getText("SS_dialogues_NameText7"),
  getText("SS_dialogues_NameText8"),
  getText("SS_dialogues_NameText9"),
};
 

SurvivorSpeechTable["Greetings"] = {
  getText("SS_dialogues_Greetings1"),
  getText("SS_dialogues_Greetings2"),
  getText("SS_dialogues_Greetings3"),
  getText("SS_dialogues_Greetings4"),
  getText("SS_dialogues_Greetings5"),
  getText("SS_dialogues_Greetings6"),
  getText("SS_dialogues_Greetings7"),
  getText("SS_dialogues_Greetings8"),
  getText("SS_dialogues_Greetings9"),
  getText("SS_dialogues_Greetings10"),
  getText("SS_dialogues_Greetings11"),
  getText("SS_dialogues_Greetings12"),
  getText("SS_dialogues_Greetings13"),
  getText("SS_dialogues_Greetings14"),
  getText("SS_dialogues_Greetings15"),
  getText("SS_dialogues_Greetings16"),
  getText("SS_dialogues_Greetings17"),
  getText("SS_dialogues_Greetings18"),
  getText("SS_dialogues_Greetings19"),
  getText("SS_dialogues_Greetings20"),
  getText("SS_dialogues_Greetings21"),
  getText("SS_dialogues_Greetings22"),
  getText("SS_dialogues_Greetings23"),
  getText("SS_dialogues_Greetings24"),
  getText("SS_dialogues_Greetings25"),
  getText("SS_dialogues_Greetings26"),
  getText("SS_dialogues_Greetings27"),
  getText("SS_dialogues_Greetings28"),
  getText("SS_dialogues_Greetings29"),
  getText("SS_dialogues_Greetings30"),
  getText("SS_dialogues_Greetings31"),
  getText("SS_dialogues_Greetings32"),
  getText("SS_dialogues_Greetings33"),
  getText("SS_dialogues_Greetings34"),
  getText("SS_dialogues_Greetings35"),
  getText("SS_dialogues_Greetings36"),
  getText("SS_dialogues_Greetings37"),
  getText("SS_dialogues_Greetings38"),
  getText("SS_dialogues_Greetings39"),
  getText("SS_dialogues_Greetings40"),
  getText("SS_dialogues_Greetings41"),
  getText("SS_dialogues_Greetings42"),
  getText("SS_dialogues_Greetings43"),
  getText("SS_dialogues_Greetings44"),
  getText("SS_dialogues_Greetings45"),
  getText("SS_dialogues_Greetings46"),
};
 

SurvivorSpeechTable["WantToHide"] = {
  getText("SS_dialogues_WantToHide1"),
  getText("SS_dialogues_WantToHide2"),
  getText("SS_dialogues_WantToHide3"),
  getText("SS_dialogues_WantToHide4"),
  getText("SS_dialogues_WantToHide5"),
  getText("SS_dialogues_WantToHide6"),
  getText("SS_dialogues_WantToHide7"),
  getText("SS_dialogues_WantToHide8"),
  getText("SS_dialogues_WantToHide9"),
  getText("SS_dialogues_WantToHide10"),
  getText("SS_dialogues_WantToHide11"),
  getText("SS_dialogues_WantToHide12"),
  getText("SS_dialogues_WantToHide13"),
  getText("SS_dialogues_WantToHide14"),
  getText("SS_dialogues_WantToHide15"),
  getText("SS_dialogues_WantToHide16"),
  getText("SS_dialogues_WantToHide17"),
  getText("SS_dialogues_WantToHide18"),
  getText("SS_dialogues_WantToHide19"),
  getText("SS_dialogues_WantToHide20"),
  getText("SS_dialogues_WantToHide21"),
  getText("SS_dialogues_WantToHide22"),
  getText("SS_dialogues_WantToHide23"),
};
 

 
SurvivorSpeechTable["FoundHidingPlace"] = {
  getText("SS_dialogues_FoundHidingPlace1"),
  getText("SS_dialogues_FoundHidingPlace2"),
  getText("SS_dialogues_FoundHidingPlace3"),
  getText("SS_dialogues_FoundHidingPlace4"),
  getText("SS_dialogues_FoundHidingPlace5"),
  getText("SS_dialogues_FoundHidingPlace6"),
  getText("SS_dialogues_FoundHidingPlace7"),
  getText("SS_dialogues_FoundHidingPlace8"),
  getText("SS_dialogues_FoundHidingPlace9"),
  getText("SS_dialogues_FoundHidingPlace10"),
  getText("SS_dialogues_FoundHidingPlace11"),
  getText("SS_dialogues_FoundHidingPlace12"),
  getText("SS_dialogues_FoundHidingPlace13"),
  getText("SS_dialogues_FoundHidingPlace14"),
  getText("SS_dialogues_FoundHidingPlace15"),
  getText("SS_dialogues_FoundHidingPlace16"),
  getText("SS_dialogues_FoundHidingPlace17"),
  getText("SS_dialogues_FoundHidingPlace18"),
  getText("SS_dialogues_FoundHidingPlace19"),
  getText("SS_dialogues_FoundHidingPlace20"),
  getText("SS_dialogues_FoundHidingPlace21"),
  getText("SS_dialogues_FoundHidingPlace22"),
  getText("SS_dialogues_FoundHidingPlace23"),
  getText("SS_dialogues_FoundHidingPlace24"),
  getText("SS_dialogues_FoundHidingPlace25"),
  getText("SS_dialogues_FoundHidingPlace26"),
  getText("SS_dialogues_FoundHidingPlace27"),
  getText("SS_dialogues_FoundHidingPlace28"),
  getText("SS_dialogues_FoundHidingPlace29"),
  getText("SS_dialogues_FoundHidingPlace30"),
  getText("SS_dialogues_FoundHidingPlace31"),
  getText("SS_dialogues_FoundHidingPlace32"),
  getText("SS_dialogues_FoundHidingPlace33"),
  getText("SS_dialogues_FoundHidingPlace34"),
  getText("SS_dialogues_FoundHidingPlace35"),
  getText("SS_dialogues_FoundHidingPlace36"),
  getText("SS_dialogues_FoundHidingPlace37"),
  getText("SS_dialogues_FoundHidingPlace38"),
  getText("SS_dialogues_FoundHidingPlace39"),
  getText("SS_dialogues_FoundHidingPlace40"),
  getText("SS_dialogues_FoundHidingPlace41"),
};
 

SurvivorSpeechTable["NoWhereToHide"] = {
  getText("SS_dialogues_NoWhereToHide1"),
  getText("SS_dialogues_NoWhereToHide2"),
  getText("SS_dialogues_NoWhereToHide3"),
  getText("SS_dialogues_NoWhereToHide4"),
  getText("SS_dialogues_NoWhereToHide5"),
  getText("SS_dialogues_NoWhereToHide6"),
  getText("SS_dialogues_NoWhereToHide7"),
  getText("SS_dialogues_NoWhereToHide8"),
  getText("SS_dialogues_NoWhereToHide9"),
  getText("SS_dialogues_NoWhereToHide10"),
  getText("SS_dialogues_NoWhereToHide11"),
  getText("SS_dialogues_NoWhereToHide12"),
  getText("SS_dialogues_NoWhereToHide13"),
  getText("SS_dialogues_NoWhereToHide14"),
  getText("SS_dialogues_NoWhereToHide15"),
  getText("SS_dialogues_NoWhereToHide16"),
  getText("SS_dialogues_NoWhereToHide17"),
  getText("SS_dialogues_NoWhereToHide18"),
  getText("SS_dialogues_NoWhereToHide19"),
  getText("SS_dialogues_NoWhereToHide20"),
  getText("SS_dialogues_NoWhereToHide21"),
  getText("SS_dialogues_NoWhereToHide22"),
  getText("SS_dialogues_NoWhereToHide23"),
};
 

SurvivorSpeechTable["Panic"] = {
  getText("SS_dialogues_Panic1"),
  getText("SS_dialogues_Panic2"),
  getText("SS_dialogues_Panic3"),
  getText("SS_dialogues_Panic4"),
  getText("SS_dialogues_Panic5"),
  getText("SS_dialogues_Panic6"),
  getText("SS_dialogues_Panic7"),
  getText("SS_dialogues_Panic8"),
  getText("SS_dialogues_Panic9"),
  getText("SS_dialogues_Panic10"),
  getText("SS_dialogues_Panic11"),
  getText("SS_dialogues_Panic12"),
  getText("SS_dialogues_Panic13"),
  getText("SS_dialogues_Panic14"),
  getText("SS_dialogues_Panic15"),
  getText("SS_dialogues_Panic16"),
  getText("SS_dialogues_Panic17"),
  getText("SS_dialogues_Panic18"),
  getText("SS_dialogues_Panic19"),
  getText("SS_dialogues_Panic20"),
  getText("SS_dialogues_Panic21"),
  getText("SS_dialogues_Panic22"),
  getText("SS_dialogues_Panic23"),
};
 

SurvivorSpeechTable["Scared"] = {
  getText("SS_dialogues_Scared1"),
  getText("SS_dialogues_Scared2"),
  getText("SS_dialogues_Scared3"),
  getText("SS_dialogues_Scared4"),
  getText("SS_dialogues_Scared5"),
  getText("SS_dialogues_Scared6"),
  getText("SS_dialogues_Scared7"),
  getText("SS_dialogues_Scared8"),
  getText("SS_dialogues_Scared9"),
  getText("SS_dialogues_Scared10"),
  getText("SS_dialogues_Scared11"),
  getText("SS_dialogues_Scared12"),
  getText("SS_dialogues_Scared13"),
  getText("SS_dialogues_Scared14"),
  getText("SS_dialogues_Scared15"),
  getText("SS_dialogues_Scared16"),
  getText("SS_dialogues_Scared17"),
  getText("SS_dialogues_Scared18"),
  getText("SS_dialogues_Scared19"),
  getText("SS_dialogues_Scared20"),
};
 

SurvivorSpeechTable["Screem"] = {
getText("SS_dialogues_Screem1"),
getText("SS_dialogues_Screem2"),
getText("SS_dialogues_Screem3"),
getText("SS_dialogues_Screem4"),
getText("SS_dialogues_Screem5"),
getText("SS_dialogues_Screem6"),
getText("SS_dialogues_Screem7"),
getText("SS_dialogues_Screem8"),
getText("SS_dialogues_Screem9"),
getText("SS_dialogues_Screem10"),
getText("SS_dialogues_Screem11"),
getText("SS_dialogues_Screem12"),
getText("SS_dialogues_Screem13"),
getText("SS_dialogues_Screem14"),
getText("SS_dialogues_Screem15"),
getText("SS_dialogues_Screem16"),
getText("SS_dialogues_Screem17"),
getText("SS_dialogues_Screem18"),
getText("SS_dialogues_Screem19"),
getText("SS_dialogues_Screem20"),
getText("SS_dialogues_Screem21"),
getText("SS_dialogues_Screem22"),
getText("SS_dialogues_Screem23"),
};
 

 
SurvivorSpeechTable["Attack"] = {
  getText("SS_dialogues_Attack1"),
  getText("SS_dialogues_Attack2"),
  getText("SS_dialogues_Attack3"),
  getText("SS_dialogues_Attack4"),
  getText("SS_dialogues_Attack5"),
  getText("SS_dialogues_Attack6"),
  getText("SS_dialogues_Attack7"),
  getText("SS_dialogues_Attack8"),
  getText("SS_dialogues_Attack9"),
  getText("SS_dialogues_Attack10"),
  getText("SS_dialogues_Attack11"),
  getText("SS_dialogues_Attack12"),
  getText("SS_dialogues_Attack13"),
  getText("SS_dialogues_Attack14"),
  getText("SS_dialogues_Attack15"),
  getText("SS_dialogues_Attack16"),
  getText("SS_dialogues_Attack17"),
  getText("SS_dialogues_Attack18"),
  getText("SS_dialogues_Attack19"),
  getText("SS_dialogues_Attack20"),
  getText("SS_dialogues_Attack21"),
  getText("SS_dialogues_Attack22"),
  getText("SS_dialogues_Attack23"),
  getText("SS_dialogues_Attack24"),
  getText("SS_dialogues_Attack25"),
  getText("SS_dialogues_Attack26"),
  getText("SS_dialogues_Attack27"),
  getText("SS_dialogues_Attack28"),
  getText("SS_dialogues_Attack29"),
  getText("SS_dialogues_Attack30"),
  getText("SS_dialogues_Attack31"),
  getText("SS_dialogues_Attack32"),
  getText("SS_dialogues_Attack33"),
  getText("SS_dialogues_Attack34"),
  getText("SS_dialogues_Attack35"),
  getText("SS_dialogues_Attack36"),
  getText("SS_dialogues_Attack37"),
  getText("SS_dialogues_Attack38"),
};

 
SurvivorSpeechTable["AttackS"] = {
  getText("SS_dialogues_AttackS1"),
  getText("SS_dialogues_AttackS2"),
  getText("SS_dialogues_AttackS3"),
  getText("SS_dialogues_AttackS4"),
  getText("SS_dialogues_AttackS5"),
  getText("SS_dialogues_AttackS6"),
  getText("SS_dialogues_AttackS7"),
  getText("SS_dialogues_AttackS8"),
  getText("SS_dialogues_AttackS9"),
  getText("SS_dialogues_AttackS10"),
  getText("SS_dialogues_AttackS11"),
  getText("SS_dialogues_AttackS12"),
  getText("SS_dialogues_AttackS13"),
  getText("SS_dialogues_AttackS14"),
  getText("SS_dialogues_AttackS15"),
  getText("SS_dialogues_AttackS16"),
  getText("SS_dialogues_AttackS17"),
  getText("SS_dialogues_AttackS18"),
  getText("SS_dialogues_AttackS19"),
  getText("SS_dialogues_AttackS20"),
  getText("SS_dialogues_AttackS21"),
  getText("SS_dialogues_AttackS22"),
  getText("SS_dialogues_AttackS23"),
  getText("SS_dialogues_AttackS24"),
  getText("SS_dialogues_AttackS25"),
  getText("SS_dialogues_AttackS26"),
  getText("SS_dialogues_AttackS27"),
  getText("SS_dialogues_AttackS28"),
  getText("SS_dialogues_AttackS29"),
};
 

SurvivorSpeechTable["Traitor"] = {
  getText("SS_dialogues_Traitor1"),
  getText("SS_dialogues_Traitor2"),
  getText("SS_dialogues_Traitor3"),
  getText("SS_dialogues_Traitor4"),
  getText("SS_dialogues_Traitor5"),
  getText("SS_dialogues_Traitor6"),
  getText("SS_dialogues_Traitor7"),
  getText("SS_dialogues_Traitor8"),
  getText("SS_dialogues_Traitor9"),
  getText("SS_dialogues_Traitor10"),
  getText("SS_dialogues_Traitor11"),
  getText("SS_dialogues_Traitor12"),
  getText("SS_dialogues_Traitor13"),
  getText("SS_dialogues_Traitor14"),
  getText("SS_dialogues_Traitor15"),
  getText("SS_dialogues_Traitor16"),
  getText("SS_dialogues_Traitor17"),
  getText("SS_dialogues_Traitor18"),
  getText("SS_dialogues_Traitor19"),
  getText("SS_dialogues_Traitor20"),
  getText("SS_dialogues_Traitor21"),
  getText("SS_dialogues_Traitor22"),
};
 

SurvivorSpeechTable["LookingForZombie"] = {
  getText("SS_dialogues_LookingForZombie1"),
  getText("SS_dialogues_LookingForZombie2"),
  getText("SS_dialogues_LookingForZombie3"),
  getText("SS_dialogues_LookingForZombie4"),
  getText("SS_dialogues_LookingForZombie5"),
  getText("SS_dialogues_LookingForZombie6"),
  getText("SS_dialogues_LookingForZombie7"),
  getText("SS_dialogues_LookingForZombie8"),
  getText("SS_dialogues_LookingForZombie9"),
  getText("SS_dialogues_LookingForZombie10"),
  getText("SS_dialogues_LookingForZombie11"),
  getText("SS_dialogues_LookingForZombie12"),
  getText("SS_dialogues_LookingForZombie13"),
  getText("SS_dialogues_LookingForZombie14"),
  getText("SS_dialogues_LookingForZombie15"),
};
 

SurvivorSpeechTable["FoundSurvivor"] = {
  getText("SS_dialogues_FoundSurvivor1"),
  getText("SS_dialogues_FoundSurvivor2"),
  getText("SS_dialogues_FoundSurvivor3"),
  getText("SS_dialogues_FoundSurvivor4"),
  getText("SS_dialogues_FoundSurvivor5"),
  getText("SS_dialogues_FoundSurvivor6"),
  getText("SS_dialogues_FoundSurvivor7"),
  getText("SS_dialogues_FoundSurvivor8"),
  getText("SS_dialogues_FoundSurvivor9"),
  getText("SS_dialogues_FoundSurvivor10"),
  getText("SS_dialogues_FoundSurvivor11"),
  getText("SS_dialogues_FoundSurvivor12"),
  getText("SS_dialogues_FoundSurvivor13"),
  getText("SS_dialogues_FoundSurvivor14"),
  getText("SS_dialogues_FoundSurvivor15"),
  getText("SS_dialogues_FoundSurvivor16"),
  getText("SS_dialogues_FoundSurvivor17"),
  getText("SS_dialogues_FoundSurvivor18"),
  getText("SS_dialogues_FoundSurvivor19"),
  getText("SS_dialogues_FoundSurvivor20"),
  getText("SS_dialogues_FoundSurvivor21"),
  getText("SS_dialogues_FoundSurvivor22"),
  getText("SS_dialogues_FoundSurvivor23"),
  getText("SS_dialogues_FoundSurvivor24"),
  getText("SS_dialogues_FoundSurvivor25"),
  getText("SS_dialogues_FoundSurvivor26"),
  getText("SS_dialogues_FoundSurvivor27"),
  getText("SS_dialogues_FoundSurvivor28"),
  getText("SS_dialogues_FoundSurvivor29"),
  getText("SS_dialogues_FoundSurvivor30"),
  getText("SS_dialogues_FoundSurvivor31"),
  getText("SS_dialogues_FoundSurvivor32"),
  getText("SS_dialogues_FoundSurvivor33"),
  getText("SS_dialogues_FoundSurvivor34"),
};
 

SurvivorSpeechTable["FoundZombie"] = {
  getText("SS_dialogues_FoundZombie1"),
  getText("SS_dialogues_FoundZombie2"),
  getText("SS_dialogues_FoundZombie3"),
  getText("SS_dialogues_FoundZombie4"),
  getText("SS_dialogues_FoundZombie5"),
  getText("SS_dialogues_FoundZombie6"),
  getText("SS_dialogues_FoundZombie7"),
  getText("SS_dialogues_FoundZombie8"),
  getText("SS_dialogues_FoundZombie9"),
  getText("SS_dialogues_FoundZombie10"),
  getText("SS_dialogues_FoundZombie11"),
  getText("SS_dialogues_FoundZombie12"),
  getText("SS_dialogues_FoundZombie13"),
  getText("SS_dialogues_FoundZombie14"),
  getText("SS_dialogues_FoundZombie15"),
  getText("SS_dialogues_FoundZombie16"),
  getText("SS_dialogues_FoundZombie17"),
  getText("SS_dialogues_FoundZombie18"),
  getText("SS_dialogues_FoundZombie19"),
};
 