--- gets a random speech text of a dialogue list
---@param key string key of the speech
---@return string a survivor speech
function getSpeech(key)
	if(not SurvivorSpeechTable[key]) then 
		return "?" 
	end
	
	local result = ZombRand(1,#SurvivorSpeechTable[key]);
	return tostring(SurvivorSpeechTable[key][result]);
end

SuperDialogue = {  -- not being used yet
	WifeSpeech = {
		getDialogue("WifeSpeech1"),
		getDialogue("WifeSpeech2"),
		getDialogue("WifeSpeech3"),
		getDialogue("WifeSpeech4"),
		getDialogue("WifeSpeech5"),
	}
}

if not SurvivorSpeechTable then 
  SurvivorSpeechTable = {} 
end

SurvivorSpeechTable["HelloThere"] = {
  getDialogue("HiThere"),
  getDialogue("HelloThere"),
  getDialogue("HelloWord1"),
	getDialogue("HelloWord2"),
	getDialogue("HelloWord3"),
	getDialogue("HelloWord4"),
	getDialogue("HelloWord5"),
	getDialogue("HelloWord6"),
	getDialogue("HelloWord7"),
	getDialogue("HelloWord8"),
	getDialogue("HelloWord9"),
	getDialogue("HelloWord10"),
	getDialogue("HelloWord11"),
	getDialogue("HelloWord12"),
	getDialogue("HelloWord13"),
	getDialogue("HelloWord14"),
};
	
SurvivorSpeechTable["OutOfAmmo"] = {
  getDialogue("OutOfAmmo1"),
  getDialogue("OutOfAmmo2"),
  getDialogue("OutOfAmmo3"),
	getDialogue("OutOfAmmo4"),
};
	
SurvivorSpeechTable["HowDareYou"] = {
  getDialogue("HowDareYou1"),
};		
SurvivorSpeechTable["WifeIntro"] = {
  getDialogue("WifeIntro1"),
};	
	
SurvivorSpeechTable["IDontKnowHowDoctor"] = {
  getDialogue("IDontKnowHowDoctor1"),
};

SurvivorSpeechTable["IfYouThinkSo"] = {
  getDialogue("IfYouThinkSo1"),
  getDialogue("IfYouThinkSo2"),
};
     
SurvivorSpeechTable["SawHimThere"] = {
  getDialogue("SawHimThere1"),
  getDialogue("SawHimThere2"),
  getDialogue("SawHimThere3"),
	getDialogue("SawHimThere4"),
};
	
SurvivorSpeechTable["GonnaGetYou"] = {
  getDialogue("GonnaGetYou1"),
  getDialogue("GonnaGetYou2"),
  getDialogue("GonnaGetYou3"),
  getDialogue("GonnaGetYou4"),
  getDialogue("GonnaGetYou5"),
};
     
  
SurvivorSpeechTable["SeenPlayerIll"] = {
  getDialogue("SeenPlayerIll1"),
  getDialogue("SeenPlayerIll2"),
  getDialogue("SeenPlayerIll3"),
  getDialogue("SeenPlayerIll4"),
  getDialogue("SeenPlayerIll5"),
  getDialogue("SeenPlayerIll6"),
  getDialogue("SeenPlayerIll7"),
  getDialogue("SeenPlayerIll8"),
};
     
SurvivorSpeechTable["SeenPlayerBit"] = {
  getDialogue("SeenPlayerBit1"),
  getDialogue("SeenPlayerBit2"),
  getDialogue("SeenPlayerBit3"),
  getDialogue("SeenPlayerBit4"),
  getDialogue("SeenPlayerBit5"),
  getDialogue("SeenPlayerBit6"),
  getDialogue("SeenPlayerBit7"),
  getDialogue("SeenPlayerBit8"),
  getDialogue("SeenPlayerBit9"),
  getDialogue("SeenPlayerBit10"),
  getDialogue("SeenPlayerBit11"),
  getDialogue("SeenPlayerBit12"),
  getDialogue("SeenPlayerBit13"),
};
    
SurvivorSpeechTable["Crying"] = {
  getDialogue("Crying1"),
  getDialogue("Crying2"),
  getDialogue("Crying3"),
  getDialogue("Crying4"),
  getDialogue("Crying5"),
  getDialogue("Crying6"),
  getDialogue("Crying7"),
  getDialogue("Crying8"),
  getDialogue("Crying9"),
  getDialogue("Crying10"),
  getDialogue("Crying11"),
  getDialogue("Crying12"),
  getDialogue("Crying13"),
  getDialogue("Crying14"),
  getDialogue("Crying15"),
  getDialogue("Crying16"),
};
      
SurvivorSpeechTable["Tired"] = {
	getDialogue("Tired1"),
  getDialogue("Tired2"),
  getDialogue("Tired3"),
  getDialogue("Tired4"),
  getDialogue("Tired5"),
  getDialogue("Tired6"),
  getDialogue("Tired7"),
  getDialogue("Tired8"),
  getDialogue("Tired9"),
  getDialogue("Tired10"),
  getDialogue("Tired11"),
};
 

SurvivorSpeechTable["VTired"] = {
  getDialogue("VTired1"),
  getDialogue("VTired2"),
  getDialogue("VTired3"),
  getDialogue("VTired4"),
  getDialogue("VTired5"),
  getDialogue("VTired6"),
};
 

 
SurvivorSpeechTable["STired"] = {
  getDialogue("STired1"),
  getDialogue("STired2"),
  getDialogue("STired3"),
  getDialogue("STired4"),
  getDialogue("STired5"),
  getDialogue("STired6"),
  getDialogue("STired7"),
};

   
SurvivorSpeechTable["Thirsty"] = {
  getDialogue("Thirsty1"),
  getDialogue("Thirsty2"),
  getDialogue("Thirsty3"),
  getDialogue("Thirsty4"),
  getDialogue("Thirsty5"),
  getDialogue("Thirsty6"),
  getDialogue("Thirsty7"),
  getDialogue("Thirsty8"),
  getDialogue("Thirsty9"),
  getDialogue("Thirsty10"),
};
 

SurvivorSpeechTable["VThirsty"] = {
  getDialogue("VThirsty1"),
  getDialogue("VThirsty2"),
  getDialogue("VThirsty3"),
  getDialogue("VThirsty4"),
  getDialogue("VThirsty5"),
  getDialogue("VThirsty6"),
  getDialogue("VThirsty7"),
  getDialogue("VThirsty8"),
  getDialogue("VThirsty9"),
  getDialogue("VThirsty10"),
};
 

SurvivorSpeechTable["SThirsty"] = {
  getDialogue("SThirsty1"),
  getDialogue("SThirsty2"),
  getDialogue("SThirsty3"),
  getDialogue("SThirsty4"),
  getDialogue("SThirsty5"),
  getDialogue("SThirsty6"),
  getDialogue("SThirsty7"),
  getDialogue("SThirsty8"),
  getDialogue("SThirsty9"),
  getDialogue("SThirsty10"),
};

 
SurvivorSpeechTable["Respond"] = {
  getDialogue("Respond1"),
  getDialogue("Respond2"),
  getDialogue("Respond3"),
  getDialogue("Respond4"),
  getDialogue("Respond5"),
  getDialogue("Respond6"),
  getDialogue("Respond7"),
  getDialogue("Respond8"),
  getDialogue("Respond9"),
  getDialogue("Respond10"),
  getDialogue("Respond11"),
  getDialogue("Respond12"),
  getDialogue("Respond13"),
  getDialogue("Respond14"),
  getDialogue("Respond15"),
  getDialogue("Respond16"),
  getDialogue("Respond17"),
  getDialogue("Respond18"),
  getDialogue("Respond19"),
  getDialogue("Respond20"),
};
 
SurvivorSpeechTable["Sick"] = {
  getDialogue("Sick1"),
  getDialogue("Sick2"),
};
 
SurvivorSpeechTable["VSick"] = {
  getDialogue("VSick1"),
  getDialogue("VSick2"),
};
 
SurvivorSpeechTable["SSick"] = {
  getDialogue("SSick1"),
  getDialogue("SSick2"),
};
 
SurvivorSpeechTable["Hungry"] = {
  getDialogue("Hungry1"),
  getDialogue("Hungry2"),
  getDialogue("Hungry3"),
  getDialogue("Hungry4"),
  getDialogue("Hungry5"),
  getDialogue("Hungry6"),
  getDialogue("Hungry7"),
  getDialogue("Hungry8"),
  getDialogue("Hungry9"),
  getDialogue("Hungry10"),
};
 
SurvivorSpeechTable["VHungry"] = {
  getDialogue("VHungry1"),
  getDialogue("VHungry2"),
  getDialogue("VHungry3"),
  getDialogue("VHungry4"),
  getDialogue("VHungry5"),
  getDialogue("VHungry6"),
  getDialogue("VHungry7"),
  getDialogue("VHungry8"),
  getDialogue("VHungry9"),
  getDialogue("VHungry10"),
};
 

SurvivorSpeechTable["Starving"] = {
  getDialogue("Starving1"),
  getDialogue("Starving2"),
  getDialogue("Starving3"),
  getDialogue("Starving4"),
  getDialogue("Starving5"),
  getDialogue("Starving6"),
  getDialogue("Starving7"),
  getDialogue("Starving8"),
  getDialogue("Starving9"),
  getDialogue("Starving10"),
};

SurvivorSpeechTable["Roger"] = {
  getDialogue("Roger1"),
  getDialogue("Roger2"),
  getDialogue("Roger3"),
  getDialogue("Roger4"),
  getDialogue("Roger5"),
  getDialogue("Roger6"),
  getDialogue("Roger7"),
  getDialogue("Roger8"),
  getDialogue("Roger9"),
  getDialogue("Roger10"),
  getDialogue("Roger11"),
  getDialogue("Roger12"),
  getDialogue("Roger13"),
  getDialogue("Roger14"),
  getDialogue("Roger15"),
  getDialogue("Roger16"),
  getDialogue("Roger17"),
  getDialogue("Roger18"),
  getDialogue("Roger19"),
  getDialogue("Roger20"),
  getDialogue("Roger21"),
  getDialogue("Roger22"),
  getDialogue("Roger23"),
  getDialogue("Roger24"),
  getDialogue("Roger25"),
  getDialogue("Roger26"),
  getDialogue("Roger27"),
  getDialogue("Roger28"),
  getDialogue("Roger29"),
  getDialogue("Roger30"),
};
 
SurvivorSpeechTable["No"] = {
	getDialogue("No1"),
  getDialogue("No2"),
  getDialogue("No3"),
  getDialogue("No4"),
  getDialogue("No5"),
  getDialogue("No6"),
  getDialogue("No7"),
  getDialogue("No8"),
  getDialogue("No9"),
  getDialogue("No10"),
  getDialogue("No11"),
  getDialogue("No12"),
 };
 
SurvivorSpeechTable["Thanks"] = {
 getDialogue("Thanks1"),
 getDialogue("Thanks2"),
 getDialogue("Thanks3"),
 getDialogue("Thanks4"),
 getDialogue("Thanks5"),
 getDialogue("Thanks6"),
 getDialogue("Thanks7"),
 getDialogue("Thanks8"),
};

SurvivorSpeechTable["HitByPlayer"] = {
  getDialogue("HitByPlayer1"),
  getDialogue("HitByPlayer2"),
  getDialogue("HitByPlayer3"),
  getDialogue("HitByPlayer4"),
  getDialogue("HitByPlayer5"),
  getDialogue("HitByPlayer6"),
  getDialogue("HitByPlayer7"),
  getDialogue("HitByPlayer8"),
  getDialogue("HitByPlayer9"),
  getDialogue("HitByPlayer10"),
  getDialogue("HitByPlayer11"),
  getDialogue("HitByPlayer12"),
  getDialogue("HitByPlayer13"),
  getDialogue("HitByPlayer14"),
  getDialogue("HitByPlayer15"),
  getDialogue("HitByPlayer16"),
  getDialogue("HitByPlayer17"),
  getDialogue("HitByPlayer18"),
  getDialogue("HitByPlayer19"),
  getDialogue("HitByPlayer20"),
  getDialogue("HitByPlayer21"),
  getDialogue("HitByPlayer22"),
  getDialogue("HitByPlayer23"),
  getDialogue("HitByPlayer24"),
  getDialogue("HitByPlayer25"),
  getDialogue("HitByPlayer26"),
  getDialogue("HitByPlayer27"),
  getDialogue("HitByPlayer28"),
  getDialogue("HitByPlayer29"),
};

 
SurvivorSpeechTable["SeenFirstZombie"] = {
  getDialogue("SeenFirstZombie1"),
  getDialogue("SeenFirstZombie2"),
  getDialogue("SeenFirstZombie3"),
  getDialogue("SeenFirstZombie4"),
  getDialogue("SeenFirstZombie5"),
  getDialogue("SeenFirstZombie6"),
  getDialogue("SeenFirstZombie7"),
  getDialogue("SeenFirstZombie8"),
  getDialogue("SeenFirstZombie9"),
  getDialogue("SeenFirstZombie10"),
  getDialogue("SeenFirstZombie11"),
  getDialogue("SeenFirstZombie12"),
  getDialogue("SeenFirstZombie13"),
  getDialogue("SeenFirstZombie14"),
  getDialogue("SeenFirstZombie15"),
  getDialogue("SeenFirstZombie16"),
  getDialogue("SeenFirstZombie17"),
  getDialogue("SeenFirstZombie18"),
};
 

SurvivorSpeechTable["IdleChatter"] = {
  getDialogue("IdleChatter1"),
  getDialogue("IdleChatter2"),
  getDialogue("IdleChatter3"),
  getDialogue("IdleChatter4"),
  getDialogue("IdleChatter5"),
  getDialogue("IdleChatter6"),
  getDialogue("IdleChatter7"),
  getDialogue("IdleChatter8"),
  getDialogue("IdleChatter9"),
  getDialogue("IdleChatter10"),
  getDialogue("IdleChatter11"),
  getDialogue("IdleChatter12"),
  getDialogue("IdleChatter13"),
  getDialogue("IdleChatter14"),
  getDialogue("IdleChatter15"),
  getDialogue("IdleChatter16"),
  getDialogue("IdleChatter17"),
  getDialogue("IdleChatter18"),
  getDialogue("IdleChatter19"),
  getDialogue("IdleChatter20"),
  getDialogue("IdleChatter21"),
  getDialogue("IdleChatter22"),
  getDialogue("IdleChatter23"),
  getDialogue("IdleChatter24"),
  getDialogue("IdleChatter25"),
  getDialogue("IdleChatter26"),
  getDialogue("IdleChatter27"),
  getDialogue("IdleChatter28"),
  getDialogue("IdleChatter29"),
  getDialogue("IdleChatter30"),
  getDialogue("IdleChatter31"),
  getDialogue("IdleChatter32"),
  getDialogue("IdleChatter33"),
  getDialogue("IdleChatter34"),
  getDialogue("IdleChatter35"),
  getDialogue("IdleChatter36"),
  getDialogue("IdleChatter37"),
  getDialogue("IdleChatter38"),
  getDialogue("IdleChatter39"),
  getDialogue("IdleChatter40"),
  getDialogue("IdleChatter41"),
  getDialogue("IdleChatter42"),
  getDialogue("IdleChatter43"),
  getDialogue("IdleChatter44"),
  getDialogue("IdleChatter45"),
  getDialogue("IdleChatter46"),
  getDialogue("IdleChatter47"),
  getDialogue("IdleChatter48"),
  getDialogue("IdleChatter49"),
  getDialogue("IdleChatter50"),
  getDialogue("IdleChatter51"),
  getDialogue("IdleChatter52"),
  getDialogue("IdleChatter53"),
  getDialogue("IdleChatter54"),
  getDialogue("IdleChatter55"),
  getDialogue("IdleChatter56"),
  getDialogue("IdleChatter57"),
  getDialogue("IdleChatter58"),
  getDialogue("IdleChatter59"),
  getDialogue("IdleChatter60"),
  getDialogue("IdleChatter61"),
  getDialogue("IdleChatter62"),
  getDialogue("IdleChatter63"),
  getDialogue("IdleChatter64"),
  getDialogue("IdleChatter65"),
  getDialogue("IdleChatter66"),
  getDialogue("IdleChatter67"),
  getDialogue("IdleChatter68"),
  getDialogue("IdleChatter69"),
  getDialogue("IdleChatter70"),
  getDialogue("IdleChatter71"),
  getDialogue("IdleChatter72"),
  getDialogue("IdleChatter73"),
  getDialogue("IdleChatter74"),
  getDialogue("IdleChatter75"),
  getDialogue("IdleChatter76"),
  getDialogue("IdleChatter77"),
  getDialogue("IdleChatter78"),
  getDialogue("IdleChatter79"),
  getDialogue("IdleChatter80"),
  getDialogue("IdleChatter81"),
  getDialogue("IdleChatter82"),
  getDialogue("IdleChatter83"),
  getDialogue("IdleChatter84"),
  getDialogue("IdleChatter85"),
  getDialogue("IdleChatter86"),
  getDialogue("IdleChatter87"),
  getDialogue("IdleChatter88"),
  getDialogue("IdleChatter89"),
  getDialogue("IdleChatter90"),
  getDialogue("IdleChatter91"),
  getDialogue("IdleChatter92"),
  getDialogue("IdleChatter93"),
  getDialogue("IdleChatter94"),
  getDialogue("IdleChatter95"),
  getDialogue("IdleChatter96"),
  getDialogue("IdleChatter97"),
  getDialogue("IdleChatter98"),
  getDialogue("IdleChatter99"),
  getDialogue("IdleChatter100"),
  getDialogue("IdleChatter101"),
  getDialogue("IdleChatter102"),
  getDialogue("IdleChatter103"),
  getDialogue("IdleChatter104"),
  getDialogue("IdleChatter105"),
  getDialogue("IdleChatter106"),
  getDialogue("IdleChatter107"),
  getDialogue("IdleChatter108"),
  getDialogue("IdleChatter109"),
  getDialogue("IdleChatter110"),
  getDialogue("IdleChatter111"),
  getDialogue("IdleChatter112"),
  getDialogue("IdleChatter113"),
  getDialogue("IdleChatter114"),
  getDialogue("IdleChatter115"),
  getDialogue("IdleChatter116"),
  getDialogue("IdleChatter117"),
  getDialogue("IdleChatter118"),
  getDialogue("IdleChatter119"),
  getDialogue("IdleChatter120"),
  getDialogue("IdleChatter121"),
  getDialogue("IdleChatter122"),
  getDialogue("IdleChatter123"),
  getDialogue("IdleChatter124"),
  getDialogue("IdleChatter125"),
  getDialogue("IdleChatter126"),
  getDialogue("IdleChatter127"),
  getDialogue("IdleChatter128"),
  getDialogue("IdleChatter129"),
  getDialogue("IdleChatter130"),
  getDialogue("IdleChatter131"),
  getDialogue("IdleChatter132"),
  getDialogue("IdleChatter133"),
  getDialogue("IdleChatter134"),
  getDialogue("IdleChatter135"),
  getDialogue("IdleChatter136"),
  getDialogue("IdleChatter137"),
  getDialogue("IdleChatter138"),
  getDialogue("IdleChatter139"),
  getDialogue("IdleChatter140"),
};
 

SurvivorSpeechTable["PreZombieChatter"] = {
  getDialogue("PreZombieChatter1"),
  getDialogue("PreZombieChatter2"),
  getDialogue("PreZombieChatter3"),
  getDialogue("PreZombieChatter4"),
  getDialogue("PreZombieChatter5"),
  getDialogue("PreZombieChatter6"),
  getDialogue("PreZombieChatter7"),
  getDialogue("PreZombieChatter8"),
  getDialogue("PreZombieChatter9"),
  getDialogue("PreZombieChatter10"),
  getDialogue("PreZombieChatter11"),
  getDialogue("PreZombieChatter12"),
  getDialogue("PreZombieChatter13"),
  getDialogue("PreZombieChatter14"),
};
 

SurvivorSpeechTable["Hurt"] = {
  getDialogue("Hurt1"),
  getDialogue("Hurt2"),
  getDialogue("Hurt3"),
  getDialogue("Hurt4"),
  getDialogue("Hurt5"),
  getDialogue("Hurt6"),
  getDialogue("Hurt7"),
  getDialogue("Hurt8"),
  getDialogue("Hurt9"),
  getDialogue("Hurt10"),
  getDialogue("Hurt11"),
  getDialogue("Hurt12"),
  getDialogue("Hurt13"),
  getDialogue("Hurt14"),
  getDialogue("Hurt15"),
  getDialogue("Hurt16"),
  getDialogue("Hurt17"),
  getDialogue("Hurt18"),
};
 

SurvivorSpeechTable["Injured"] = {
  getDialogue("Injured1"),
  getDialogue("Injured2"),
  getDialogue("Injured3"),
  getDialogue("Injured4"),
  getDialogue("Injured5"),
  getDialogue("Injured6"),
  getDialogue("Injured7"),
  getDialogue("Injured8"),
  getDialogue("Injured9"),
  getDialogue("Injured10"),
  getDialogue("Injured11"),
  getDialogue("Injured12"),
  getDialogue("Injured13"),
  getDialogue("Injured14"),
  getDialogue("Injured15"),
  getDialogue("Injured16"),
  getDialogue("Injured17"),
  getDialogue("Injured18"),
  getDialogue("Injured19"),
  getDialogue("Injured20"),
};
 

 
SurvivorSpeechTable["BadInjured"] = {
  getDialogue("BadInjured1"),
  getDialogue("BadInjured2"),
  getDialogue("BadInjured3"),
  getDialogue("BadInjured4"),
  getDialogue("BadInjured5"),
  getDialogue("BadInjured6"),
  getDialogue("BadInjured7"),
  getDialogue("BadInjured8"),
  getDialogue("BadInjured9"),
  getDialogue("BadInjured10"),
  getDialogue("BadInjured11"),
  getDialogue("BadInjured12"),
  getDialogue("BadInjured13"),
  getDialogue("BadInjured14"),
  getDialogue("BadInjured15"),
  getDialogue("BadInjured16"),
  getDialogue("BadInjured17"),
};
 

SurvivorSpeechTable["SeriousInjured"] = {
  getDialogue("SeriousInjured1"),
  getDialogue("SeriousInjured2"),
  getDialogue("SeriousInjured3"),
  getDialogue("SeriousInjured4"),
  getDialogue("SeriousInjured5"),
  getDialogue("SeriousInjured6"),
  getDialogue("SeriousInjured7"),
  getDialogue("SeriousInjured8"),
  getDialogue("SeriousInjured9"),
  getDialogue("SeriousInjured10"),
  getDialogue("SeriousInjured11"),
  getDialogue("SeriousInjured12"),
  getDialogue("SeriousInjured13"),
  getDialogue("SeriousInjured14"),
  getDialogue("SeriousInjured15"),
  getDialogue("SeriousInjured16"),
  getDialogue("SeriousInjured17"),
  getDialogue("SeriousInjured18"),
  getDialogue("SeriousInjured19"),
  getDialogue("SeriousInjured20"),
  getDialogue("SeriousInjured21"),
  getDialogue("SeriousInjured22"),
  getDialogue("SeriousInjured23"),
};
 

SurvivorSpeechTable["FatalInjured"] = {
  getDialogue("FatalInjured1"),
  getDialogue("FatalInjured2"),
  getDialogue("FatalInjured3"),
  getDialogue("FatalInjured4"),
  getDialogue("FatalInjured5"),
  getDialogue("FatalInjured6"),
  getDialogue("FatalInjured7"),
  getDialogue("FatalInjured8"),
  getDialogue("FatalInjured9"),
  getDialogue("FatalInjured10"),
  getDialogue("FatalInjured11"),
  getDialogue("FatalInjured12"),
  getDialogue("FatalInjured13"),
  getDialogue("FatalInjured14"),
  getDialogue("FatalInjured15"),
  getDialogue("FatalInjured16"),
  getDialogue("FatalInjured17"),
};
 

SurvivorSpeechTable["FinalWords"] = {
  getDialogue("FinalWords1"),
  getDialogue("FinalWords2"),
  getDialogue("FinalWords3"),
  getDialogue("FinalWords4"),
  getDialogue("FinalWords5"),
  getDialogue("FinalWords6"),
  getDialogue("FinalWords7"),
  getDialogue("FinalWords8"),
  getDialogue("FinalWords9"),
  getDialogue("FinalWords10"),
  getDialogue("FinalWords11"),
  getDialogue("FinalWords12"),
  getDialogue("FinalWords13"),
  getDialogue("FinalWords14"),
  getDialogue("FinalWords15"),
  getDialogue("FinalWords16"),
  getDialogue("FinalWords17"),
  getDialogue("FinalWords18"),
  getDialogue("FinalWords19"),
  getDialogue("FinalWords20"),
  getDialogue("FinalWords21"),
  getDialogue("FinalWords22"),
  getDialogue("FinalWords23"),
  getDialogue("FinalWords24"),
  getDialogue("FinalWords25"),
  getDialogue("FinalWords26"),
  getDialogue("FinalWords27"),
  getDialogue("FinalWords28"),
  getDialogue("FinalWords29"),
  getDialogue("FinalWords30"),
  getDialogue("FinalWords31"),
};
 

 
SurvivorSpeechTable["NameText"] = {
  getDialogue("NameText1"),
  getDialogue("NameText2"),
  getDialogue("NameText3"),
  getDialogue("NameText4"),
  getDialogue("NameText5"),
  getDialogue("NameText6"),
  getDialogue("NameText7"),
  getDialogue("NameText8"),
  getDialogue("NameText9"),
};
 

SurvivorSpeechTable["Greetings"] = {
  getDialogue("Greetings1"),
  getDialogue("Greetings2"),
  getDialogue("Greetings3"),
  getDialogue("Greetings4"),
  getDialogue("Greetings5"),
  getDialogue("Greetings6"),
  getDialogue("Greetings7"),
  getDialogue("Greetings8"),
  getDialogue("Greetings9"),
  getDialogue("Greetings10"),
  getDialogue("Greetings11"),
  getDialogue("Greetings12"),
  getDialogue("Greetings13"),
  getDialogue("Greetings14"),
  getDialogue("Greetings15"),
  getDialogue("Greetings16"),
  getDialogue("Greetings17"),
  getDialogue("Greetings18"),
  getDialogue("Greetings19"),
  getDialogue("Greetings20"),
  getDialogue("Greetings21"),
  getDialogue("Greetings22"),
  getDialogue("Greetings23"),
  getDialogue("Greetings24"),
  getDialogue("Greetings25"),
  getDialogue("Greetings26"),
  getDialogue("Greetings27"),
  getDialogue("Greetings28"),
  getDialogue("Greetings29"),
  getDialogue("Greetings30"),
  getDialogue("Greetings31"),
  getDialogue("Greetings32"),
  getDialogue("Greetings33"),
  getDialogue("Greetings34"),
  getDialogue("Greetings35"),
  getDialogue("Greetings36"),
  getDialogue("Greetings37"),
  getDialogue("Greetings38"),
  getDialogue("Greetings39"),
  getDialogue("Greetings40"),
  getDialogue("Greetings41"),
  getDialogue("Greetings42"),
  getDialogue("Greetings43"),
  getDialogue("Greetings44"),
  getDialogue("Greetings45"),
  getDialogue("Greetings46"),
};
 

SurvivorSpeechTable["WantToHide"] = {
  getDialogue("WantToHide1"),
  getDialogue("WantToHide2"),
  getDialogue("WantToHide3"),
  getDialogue("WantToHide4"),
  getDialogue("WantToHide5"),
  getDialogue("WantToHide6"),
  getDialogue("WantToHide7"),
  getDialogue("WantToHide8"),
  getDialogue("WantToHide9"),
  getDialogue("WantToHide10"),
  getDialogue("WantToHide11"),
  getDialogue("WantToHide12"),
  getDialogue("WantToHide13"),
  getDialogue("WantToHide14"),
  getDialogue("WantToHide15"),
  getDialogue("WantToHide16"),
  getDialogue("WantToHide17"),
  getDialogue("WantToHide18"),
  getDialogue("WantToHide19"),
  getDialogue("WantToHide20"),
  getDialogue("WantToHide21"),
  getDialogue("WantToHide22"),
  getDialogue("WantToHide23"),
};
 

 
SurvivorSpeechTable["FoundHidingPlace"] = {
  getDialogue("FoundHidingPlace1"),
  getDialogue("FoundHidingPlace2"),
  getDialogue("FoundHidingPlace3"),
  getDialogue("FoundHidingPlace4"),
  getDialogue("FoundHidingPlace5"),
  getDialogue("FoundHidingPlace6"),
  getDialogue("FoundHidingPlace7"),
  getDialogue("FoundHidingPlace8"),
  getDialogue("FoundHidingPlace9"),
  getDialogue("FoundHidingPlace10"),
  getDialogue("FoundHidingPlace11"),
  getDialogue("FoundHidingPlace12"),
  getDialogue("FoundHidingPlace13"),
  getDialogue("FoundHidingPlace14"),
  getDialogue("FoundHidingPlace15"),
  getDialogue("FoundHidingPlace16"),
  getDialogue("FoundHidingPlace17"),
  getDialogue("FoundHidingPlace18"),
  getDialogue("FoundHidingPlace19"),
  getDialogue("FoundHidingPlace20"),
  getDialogue("FoundHidingPlace21"),
  getDialogue("FoundHidingPlace22"),
  getDialogue("FoundHidingPlace23"),
  getDialogue("FoundHidingPlace24"),
  getDialogue("FoundHidingPlace25"),
  getDialogue("FoundHidingPlace26"),
  getDialogue("FoundHidingPlace27"),
  getDialogue("FoundHidingPlace28"),
  getDialogue("FoundHidingPlace29"),
  getDialogue("FoundHidingPlace30"),
  getDialogue("FoundHidingPlace31"),
  getDialogue("FoundHidingPlace32"),
  getDialogue("FoundHidingPlace33"),
  getDialogue("FoundHidingPlace34"),
  getDialogue("FoundHidingPlace35"),
  getDialogue("FoundHidingPlace36"),
  getDialogue("FoundHidingPlace37"),
  getDialogue("FoundHidingPlace38"),
  getDialogue("FoundHidingPlace39"),
  getDialogue("FoundHidingPlace40"),
  getDialogue("FoundHidingPlace41"),
};
 

SurvivorSpeechTable["NoWhereToHide"] = {
  getDialogue("NoWhereToHide1"),
  getDialogue("NoWhereToHide2"),
  getDialogue("NoWhereToHide3"),
  getDialogue("NoWhereToHide4"),
  getDialogue("NoWhereToHide5"),
  getDialogue("NoWhereToHide6"),
  getDialogue("NoWhereToHide7"),
  getDialogue("NoWhereToHide8"),
  getDialogue("NoWhereToHide9"),
  getDialogue("NoWhereToHide10"),
  getDialogue("NoWhereToHide11"),
  getDialogue("NoWhereToHide12"),
  getDialogue("NoWhereToHide13"),
  getDialogue("NoWhereToHide14"),
  getDialogue("NoWhereToHide15"),
  getDialogue("NoWhereToHide16"),
  getDialogue("NoWhereToHide17"),
  getDialogue("NoWhereToHide18"),
  getDialogue("NoWhereToHide19"),
  getDialogue("NoWhereToHide20"),
  getDialogue("NoWhereToHide21"),
  getDialogue("NoWhereToHide22"),
  getDialogue("NoWhereToHide23"),
};
 

SurvivorSpeechTable["Panic"] = {
  getDialogue("Panic1"),
  getDialogue("Panic2"),
  getDialogue("Panic3"),
  getDialogue("Panic4"),
  getDialogue("Panic5"),
  getDialogue("Panic6"),
  getDialogue("Panic7"),
  getDialogue("Panic8"),
  getDialogue("Panic9"),
  getDialogue("Panic10"),
  getDialogue("Panic11"),
  getDialogue("Panic12"),
  getDialogue("Panic13"),
  getDialogue("Panic14"),
  getDialogue("Panic15"),
  getDialogue("Panic16"),
  getDialogue("Panic17"),
  getDialogue("Panic18"),
  getDialogue("Panic19"),
  getDialogue("Panic20"),
  getDialogue("Panic21"),
  getDialogue("Panic22"),
  getDialogue("Panic23"),
};
 

SurvivorSpeechTable["Scared"] = {
  getDialogue("Scared1"),
  getDialogue("Scared2"),
  getDialogue("Scared3"),
  getDialogue("Scared4"),
  getDialogue("Scared5"),
  getDialogue("Scared6"),
  getDialogue("Scared7"),
  getDialogue("Scared8"),
  getDialogue("Scared9"),
  getDialogue("Scared10"),
  getDialogue("Scared11"),
  getDialogue("Scared12"),
  getDialogue("Scared13"),
  getDialogue("Scared14"),
  getDialogue("Scared15"),
  getDialogue("Scared16"),
  getDialogue("Scared17"),
  getDialogue("Scared18"),
  getDialogue("Scared19"),
  getDialogue("Scared20"),
};
 

SurvivorSpeechTable["Screem"] = {
getDialogue("Screem1"),
getDialogue("Screem2"),
getDialogue("Screem3"),
getDialogue("Screem4"),
getDialogue("Screem5"),
getDialogue("Screem6"),
getDialogue("Screem7"),
getDialogue("Screem8"),
getDialogue("Screem9"),
getDialogue("Screem10"),
getDialogue("Screem11"),
getDialogue("Screem12"),
getDialogue("Screem13"),
getDialogue("Screem14"),
getDialogue("Screem15"),
getDialogue("Screem16"),
getDialogue("Screem17"),
getDialogue("Screem18"),
getDialogue("Screem19"),
getDialogue("Screem20"),
getDialogue("Screem21"),
getDialogue("Screem22"),
getDialogue("Screem23"),
};
 

 
SurvivorSpeechTable["Attack"] = {
  getDialogue("Attack1"),
  getDialogue("Attack2"),
  getDialogue("Attack3"),
  getDialogue("Attack4"),
  getDialogue("Attack5"),
  getDialogue("Attack6"),
  getDialogue("Attack7"),
  getDialogue("Attack8"),
  getDialogue("Attack9"),
  getDialogue("Attack10"),
  getDialogue("Attack11"),
  getDialogue("Attack12"),
  getDialogue("Attack13"),
  getDialogue("Attack14"),
  getDialogue("Attack15"),
  getDialogue("Attack16"),
  getDialogue("Attack17"),
  getDialogue("Attack18"),
  getDialogue("Attack19"),
  getDialogue("Attack20"),
  getDialogue("Attack21"),
  getDialogue("Attack22"),
  getDialogue("Attack23"),
  getDialogue("Attack24"),
  getDialogue("Attack25"),
  getDialogue("Attack26"),
  getDialogue("Attack27"),
  getDialogue("Attack28"),
  getDialogue("Attack29"),
  getDialogue("Attack30"),
  getDialogue("Attack31"),
  getDialogue("Attack32"),
  getDialogue("Attack33"),
  getDialogue("Attack34"),
  getDialogue("Attack35"),
  getDialogue("Attack36"),
  getDialogue("Attack37"),
  getDialogue("Attack38"),
};

 
SurvivorSpeechTable["AttackS"] = {
  getDialogue("AttackS1"),
  getDialogue("AttackS2"),
  getDialogue("AttackS3"),
  getDialogue("AttackS4"),
  getDialogue("AttackS5"),
  getDialogue("AttackS6"),
  getDialogue("AttackS7"),
  getDialogue("AttackS8"),
  getDialogue("AttackS9"),
  getDialogue("AttackS10"),
  getDialogue("AttackS11"),
  getDialogue("AttackS12"),
  getDialogue("AttackS13"),
  getDialogue("AttackS14"),
  getDialogue("AttackS15"),
  getDialogue("AttackS16"),
  getDialogue("AttackS17"),
  getDialogue("AttackS18"),
  getDialogue("AttackS19"),
  getDialogue("AttackS20"),
  getDialogue("AttackS21"),
  getDialogue("AttackS22"),
  getDialogue("AttackS23"),
  getDialogue("AttackS24"),
  getDialogue("AttackS25"),
  getDialogue("AttackS26"),
  getDialogue("AttackS27"),
  getDialogue("AttackS28"),
  getDialogue("AttackS29"),
};
 

SurvivorSpeechTable["Traitor"] = {
  getDialogue("Traitor1"),
  getDialogue("Traitor2"),
  getDialogue("Traitor3"),
  getDialogue("Traitor4"),
  getDialogue("Traitor5"),
  getDialogue("Traitor6"),
  getDialogue("Traitor7"),
  getDialogue("Traitor8"),
  getDialogue("Traitor9"),
  getDialogue("Traitor10"),
  getDialogue("Traitor11"),
  getDialogue("Traitor12"),
  getDialogue("Traitor13"),
  getDialogue("Traitor14"),
  getDialogue("Traitor15"),
  getDialogue("Traitor16"),
  getDialogue("Traitor17"),
  getDialogue("Traitor18"),
  getDialogue("Traitor19"),
  getDialogue("Traitor20"),
  getDialogue("Traitor21"),
  getDialogue("Traitor22"),
};
 

SurvivorSpeechTable["LookingForZombie"] = {
  getDialogue("LookingForZombie1"),
  getDialogue("LookingForZombie2"),
  getDialogue("LookingForZombie3"),
  getDialogue("LookingForZombie4"),
  getDialogue("LookingForZombie5"),
  getDialogue("LookingForZombie6"),
  getDialogue("LookingForZombie7"),
  getDialogue("LookingForZombie8"),
  getDialogue("LookingForZombie9"),
  getDialogue("LookingForZombie10"),
  getDialogue("LookingForZombie11"),
  getDialogue("LookingForZombie12"),
  getDialogue("LookingForZombie13"),
  getDialogue("LookingForZombie14"),
  getDialogue("LookingForZombie15"),
};
 

SurvivorSpeechTable["FoundSurvivor"] = {
  getDialogue("FoundSurvivor1"),
  getDialogue("FoundSurvivor2"),
  getDialogue("FoundSurvivor3"),
  getDialogue("FoundSurvivor4"),
  getDialogue("FoundSurvivor5"),
  getDialogue("FoundSurvivor6"),
  getDialogue("FoundSurvivor7"),
  getDialogue("FoundSurvivor8"),
  getDialogue("FoundSurvivor9"),
  getDialogue("FoundSurvivor10"),
  getDialogue("FoundSurvivor11"),
  getDialogue("FoundSurvivor12"),
  getDialogue("FoundSurvivor13"),
  getDialogue("FoundSurvivor14"),
  getDialogue("FoundSurvivor15"),
  getDialogue("FoundSurvivor16"),
  getDialogue("FoundSurvivor17"),
  getDialogue("FoundSurvivor18"),
  getDialogue("FoundSurvivor19"),
  getDialogue("FoundSurvivor20"),
  getDialogue("FoundSurvivor21"),
  getDialogue("FoundSurvivor22"),
  getDialogue("FoundSurvivor23"),
  getDialogue("FoundSurvivor24"),
  getDialogue("FoundSurvivor25"),
  getDialogue("FoundSurvivor26"),
  getDialogue("FoundSurvivor27"),
  getDialogue("FoundSurvivor28"),
  getDialogue("FoundSurvivor29"),
  getDialogue("FoundSurvivor30"),
  getDialogue("FoundSurvivor31"),
  getDialogue("FoundSurvivor32"),
  getDialogue("FoundSurvivor33"),
  getDialogue("FoundSurvivor34"),
};
 

SurvivorSpeechTable["FoundZombie"] = {
  getDialogue("FoundZombie1"),
  getDialogue("FoundZombie2"),
  getDialogue("FoundZombie3"),
  getDialogue("FoundZombie4"),
  getDialogue("FoundZombie5"),
  getDialogue("FoundZombie6"),
  getDialogue("FoundZombie7"),
  getDialogue("FoundZombie8"),
  getDialogue("FoundZombie9"),
  getDialogue("FoundZombie10"),
  getDialogue("FoundZombie11"),
  getDialogue("FoundZombie12"),
  getDialogue("FoundZombie13"),
  getDialogue("FoundZombie14"),
  getDialogue("FoundZombie15"),
  getDialogue("FoundZombie16"),
  getDialogue("FoundZombie17"),
  getDialogue("FoundZombie18"),
  getDialogue("FoundZombie19"),
};
 