
OrderDesc = {}
OrderDesc["Barricade"] = getText("ContextMenu_OrderDesc_Barricade")
OrderDesc["Farming"] = getText("ContextMenu_OrderDesc_Farming")
OrderDesc["Chop Wood"] = getText("ContextMenu_OrderDesc_Chop_Wood")
OrderDesc["Explore"] = getText("ContextMenu_OrderDesc_Explore")
OrderDesc["Follow"] = getText("ContextMenu_OrderDesc_Follow")
OrderDesc["Forage"] = getText("ContextMenu_OrderDesc_Forage")
OrderDesc["Guard"] = getText("ContextMenu_OrderDesc_Guard")
OrderDesc["Patrol"] = getText("ContextMenu_OrderDesc_Patrol")
OrderDesc["Stand Ground"] = getText("ContextMenu_OrderDesc_Stand_Ground")
OrderDesc["Loot Room"] = getText("ContextMenu_OrderDesc_Loot_Room")
OrderDesc["Lock Doors"] = getText("ContextMenu_OrderDesc_Lock_Doors")
OrderDesc["Unlock Doors"] = getText("ContextMenu_OrderDesc_Unlock_Doors")
OrderDesc["Doctor"] = getText("ContextMenu_OrderDesc_Doctor")
OrderDesc["Go Find Food"] = getText("ContextMenu_OrderDesc_Go_Find_Food")
OrderDesc["Go Find Weapon"] = getText("ContextMenu_OrderDesc_Go_Find_Weapon")
OrderDesc["Go Find Water"] = getText("ContextMenu_OrderDesc_Go_Find_Water")
OrderDesc["Clean Up Inventory"] = getText("ContextMenu_OrderDesc_Clean_Up_Inventory")
OrderDesc["Hold Still"] = getText("ContextMenu_OrderDesc_Hold_Still")
OrderDesc["Gather Wood"] = getText("ContextMenu_OrderDesc_Gather_Wood")
OrderDesc["Dismiss"] = getText("ContextMenu_OrderDesc_Dismiss")
OrderDesc["Relax"] = getText("ContextMenu_OrderDesc_Relax")
OrderDesc["Pile Corpses"] = getText("ContextMenu_OrderDesc_Pile_Corpses")
OrderDesc["Return To Base"] = getText("ContextMenu_OrderDesc_Return_To_Base")
OrderDesc["Stop"] = getText("ContextMenu_OrderDesc_Stop")

OrderDisplayName = {}
OrderDisplayName["Farming"] = getText("ContextMenu_OrderDisplayName_Farming")
OrderDisplayName["Barricade"] = getText("ContextMenu_OrderDisplayName_Barricade")
OrderDisplayName["Chop Wood"] = getText("ContextMenu_OrderDisplayName_Chop_Wood")
OrderDisplayName["Explore"] = getText("ContextMenu_OrderDisplayName_Explore")
OrderDisplayName["Follow"] = getText("ContextMenu_OrderDisplayName_Follow")
OrderDisplayName["Forage"] = getText("ContextMenu_OrderDisplayName_Forage")
OrderDisplayName["Guard"] = getText("ContextMenu_OrderDisplayName_Guard")
OrderDisplayName["Patrol"] = getText("ContextMenu_OrderDisplayName_Patrol")
OrderDisplayName["Stand Ground"] = getText("ContextMenu_OrderDisplayName_Stand_Ground")
OrderDisplayName["Loot Room"] = getText("ContextMenu_OrderDisplayName_Loot_Room")
OrderDisplayName["Lock Doors"] = getText("ContextMenu_OrderDisplayName_Lock_Doors")
OrderDisplayName["Unlock Doors"] = getText("ContextMenu_OrderDisplayName_Unlock_Doors")
OrderDisplayName["Doctor"] = getText("ContextMenu_OrderDisplayName_Doctor")
OrderDisplayName["Go Find Food"] = getText("ContextMenu_OrderDisplayName_Go_Find_Food")
OrderDisplayName["Go Find Weapon"] = getText("ContextMenu_OrderDisplayName_Go_Find_Weapon")
OrderDisplayName["Go Find Water"] =  getText("ContextMenu_OrderDisplayName_Go_Find_Water")
OrderDisplayName["Clean Up Inventory"] = getText("ContextMenu_OrderDisplayName_Clean_Up_Inventory")
OrderDisplayName["Hold Still"] = getText("ContextMenu_OrderDisplayName_Hold_Still")
OrderDisplayName["Gather Wood"] = getText("ContextMenu_OrderDisplayName_Gather_Wood")
OrderDisplayName["Dismiss"] = getText("ContextMenu_OrderDisplayName_Dismiss")
OrderDisplayName["Relax"] = getText("ContextMenu_OrderDisplayName_Relax")
OrderDisplayName["Pile Corpses"] = getText("ContextMenu_OrderDisplayName_Pile_Corpses")
OrderDisplayName["Return To Base"] = getText("ContextMenu_OrderDisplayName_Return_To_Base")
OrderDisplayName["Stop"] = getText("ContextMenu_OrderDisplayName_Stop")


SuperDialogue = {  -- not being used yet
	WifeSpeech = {
		getText("ContextMenu_speech_WifeSpeech1"),
		getText("ContextMenu_speech_WifeSpeech2"),
		getText("ContextMenu_speech_WifeSpeech3"),
		getText("ContextMenu_speech_WifeSpeech4"),
		getText("ContextMenu_speech_WifeSpeech5"),
	}
}

if not SurvivorSpeechTable then SurvivorSpeechTable = {} end

SurvivorSpeechTable["HelloThere"] = {
     getText("ContextMenu_SD_HiThere"),
     getText("ContextMenu_SD_HelloThere"),
     getText("ContextMenu_SD_HelloWord1"),
	 getText("ContextMenu_SD_HelloWord2"),
	 getText("ContextMenu_SD_HelloWord3"),
	 getText("ContextMenu_SD_HelloWord4"),
	 getText("ContextMenu_SD_HelloWord5"),
	 getText("ContextMenu_SD_HelloWord6"),
	 getText("ContextMenu_SD_HelloWord7"),
	 getText("ContextMenu_SD_HelloWord8"),
	 getText("ContextMenu_SD_HelloWord9"),
	 getText("ContextMenu_SD_HelloWord10"),
	 getText("ContextMenu_SD_HelloWord11"),
	 getText("ContextMenu_SD_HelloWord12"),
	 getText("ContextMenu_SD_HelloWord13"),
	 getText("ContextMenu_SD_HelloWord14"),
    };
	
SurvivorSpeechTable["OutOfAmmo"] = {
     getText("ContextMenu_speech_OutOfAmmo1"),
     getText("ContextMenu_speech_OutOfAmmo2"),
     getText("ContextMenu_speech_OutOfAmmo3"),
	 getText("ContextMenu_speech_OutOfAmmo4"),
    };
	
SurvivorSpeechTable["HowDareYou"] = {
     getText("ContextMenu_speech_HowDareYou1"),
   };		
SurvivorSpeechTable["WifeIntro"] = {
     getText("ContextMenu_speech_WifeIntro1"),
   };	
	
SurvivorSpeechTable["IDontKnowHowDoctor"] = {
     getText("ContextMenu_speech_IDontKnowHowDoctor1"),
   };

SurvivorSpeechTable["IfYouThinkSo"] = {
     getText("ContextMenu_speech_IfYouThinkSo1"),
     getText("ContextMenu_speech_IfYouThinkSo2"),
   };
     
SurvivorSpeechTable["SawHimThere"] = {
     getText("ContextMenu_speech_SawHimThere1"),
     getText("ContextMenu_speech_SawHimThere2"),
     getText("ContextMenu_speech_SawHimThere3"),
	 getText("ContextMenu_speech_SawHimThere4"),
    };
	
	SurvivorSpeechTable["GonnaGetYou"] = {
     getText("ContextMenu_speech_GonnaGetYou1"),
     getText("ContextMenu_speech_GonnaGetYou2"),
     getText("ContextMenu_speech_GonnaGetYou3"),
	 getText("ContextMenu_speech_GonnaGetYou4"),
	 getText("ContextMenu_speech_GonnaGetYou5"),
    };
     
  
SurvivorSpeechTable["SeenPlayerIll"] = {
     getText("ContextMenu_speech_SeenPlayerIll1"),
     getText("ContextMenu_speech_SeenPlayerIll2"),
     getText("ContextMenu_speech_SeenPlayerIll3"),
     getText("ContextMenu_speech_SeenPlayerIll4"),
     getText("ContextMenu_speech_SeenPlayerIll5"),
     getText("ContextMenu_speech_SeenPlayerIll6"),
     getText("ContextMenu_speech_SeenPlayerIll7"),
     getText("ContextMenu_speech_SeenPlayerIll8"),
	 };
     
   
SurvivorSpeechTable["SeenPlayerBit"] = {
     getText("ContextMenu_speech_SeenPlayerBit1"),
     getText("ContextMenu_speech_SeenPlayerBit2"),
     getText("ContextMenu_speech_SeenPlayerBit3"),
     getText("ContextMenu_speech_SeenPlayerBit4"),
     getText("ContextMenu_speech_SeenPlayerBit5"),
     getText("ContextMenu_speech_SeenPlayerBit6"),
     getText("ContextMenu_speech_SeenPlayerBit7"),
     getText("ContextMenu_speech_SeenPlayerBit8"),
     getText("ContextMenu_speech_SeenPlayerBit9"),
     getText("ContextMenu_speech_SeenPlayerBit10"),
     getText("ContextMenu_speech_SeenPlayerBit11"),
     getText("ContextMenu_speech_SeenPlayerBit12"),
     getText("ContextMenu_speech_SeenPlayerBit13"),
	 };
     

     
SurvivorSpeechTable["Crying"] = {
	getText("ContextMenu_speech_Crying1"),
 getText("ContextMenu_speech_Crying2"),
 getText("ContextMenu_speech_Crying3"),
 getText("ContextMenu_speech_Crying4"),
 getText("ContextMenu_speech_Crying5"),
 getText("ContextMenu_speech_Crying6"),
 getText("ContextMenu_speech_Crying7"),
 getText("ContextMenu_speech_Crying8"),
 getText("ContextMenu_speech_Crying9"),
 getText("ContextMenu_speech_Crying10"),
 getText("ContextMenu_speech_Crying11"),
 getText("ContextMenu_speech_Crying12"),
 getText("ContextMenu_speech_Crying13"),
 getText("ContextMenu_speech_Crying14"),
 getText("ContextMenu_speech_Crying15"),
 getText("ContextMenu_speech_Crying16"),
 };
 
      
     
      SurvivorSpeechTable["Tired"] = {
	  getText("ContextMenu_speech_Tired1"),
 getText("ContextMenu_speech_Tired2"),
 getText("ContextMenu_speech_Tired3"),
 getText("ContextMenu_speech_Tired4"),
 getText("ContextMenu_speech_Tired5"),
 getText("ContextMenu_speech_Tired6"),
 getText("ContextMenu_speech_Tired7"),
 getText("ContextMenu_speech_Tired8"),
 getText("ContextMenu_speech_Tired9"),
 getText("ContextMenu_speech_Tired10"),
 getText("ContextMenu_speech_Tired11"),
 };
 

 SurvivorSpeechTable["VTired"] = {
 getText("ContextMenu_speech_VTired1"),
 getText("ContextMenu_speech_VTired2"),
 getText("ContextMenu_speech_VTired3"),
 getText("ContextMenu_speech_VTired4"),
 getText("ContextMenu_speech_VTired5"),
  getText("ContextMenu_speech_VTired6"),
  };
 

 
  SurvivorSpeechTable["STired"] = {
  getText("ContextMenu_speech_STired1"),
 getText("ContextMenu_speech_STired2"),
getText("ContextMenu_speech_STired3"),
getText("ContextMenu_speech_STired4"),
getText("ContextMenu_speech_STired5"),
getText("ContextMenu_speech_STired6"),
getText("ContextMenu_speech_STired7"),
};

   
   SurvivorSpeechTable["Thirsty"] = {
 getText("ContextMenu_speech_Thirsty1"),
 getText("ContextMenu_speech_Thirsty2"),
 getText("ContextMenu_speech_Thirsty3"),
 getText("ContextMenu_speech_Thirsty4"),
 getText("ContextMenu_speech_Thirsty5"),
 getText("ContextMenu_speech_Thirsty6"),
 getText("ContextMenu_speech_Thirsty7"),
 getText("ContextMenu_speech_Thirsty8"),
 getText("ContextMenu_speech_Thirsty9"),
 getText("ContextMenu_speech_Thirsty10"),
  };
 

 SurvivorSpeechTable["VThirsty"] = {
 getText("ContextMenu_speech_VThirsty1"),
 getText("ContextMenu_speech_VThirsty2"),
 getText("ContextMenu_speech_VThirsty3"),
 getText("ContextMenu_speech_VThirsty4"),
 getText("ContextMenu_speech_VThirsty5"),
 getText("ContextMenu_speech_VThirsty6"),
 getText("ContextMenu_speech_VThirsty7"),
 getText("ContextMenu_speech_VThirsty8"),
 getText("ContextMenu_speech_VThirsty9"),
 getText("ContextMenu_speech_VThirsty10"),
  };
 

  SurvivorSpeechTable["SThirsty"] = {
  getText("ContextMenu_speech_SThirsty1"),
 getText("ContextMenu_speech_SThirsty2"),
 getText("ContextMenu_speech_SThirsty3"),
 getText("ContextMenu_speech_SThirsty4"),
 getText("ContextMenu_speech_SThirsty5"),
 getText("ContextMenu_speech_SThirsty6"),
 getText("ContextMenu_speech_SThirsty7"),
 getText("ContextMenu_speech_SThirsty8"),
 getText("ContextMenu_speech_SThirsty9"),
 getText("ContextMenu_speech_SThirsty10"),
 };
 

 
 
  SurvivorSpeechTable["Respond"] = {
  getText("ContextMenu_speech_Respond1"),
 getText("ContextMenu_speech_Respond2"),
 getText("ContextMenu_speech_Respond3"),
 getText("ContextMenu_speech_Respond4"),
 getText("ContextMenu_speech_Respond5"),
 getText("ContextMenu_speech_Respond6"),
 getText("ContextMenu_speech_Respond7"),
 getText("ContextMenu_speech_Respond8"),
 getText("ContextMenu_speech_Respond9"),
 getText("ContextMenu_speech_Respond10"),
 getText("ContextMenu_speech_Respond11"),
 getText("ContextMenu_speech_Respond12"),
 getText("ContextMenu_speech_Respond13"),
 getText("ContextMenu_speech_Respond14"),
 getText("ContextMenu_speech_Respond15"),
 getText("ContextMenu_speech_Respond16"),
 getText("ContextMenu_speech_Respond17"),
 getText("ContextMenu_speech_Respond18"),
 getText("ContextMenu_speech_Respond19"),
 getText("ContextMenu_speech_Respond20"),
 };
 
 SurvivorSpeechTable["Sick"] = {
   getText("ContextMenu_speech_Sick1"),
 getText("ContextMenu_speech_Sick2"),
 };
 
 SurvivorSpeechTable["VSick"] = {
   getText("ContextMenu_speech_VSick1"),
 getText("ContextMenu_speech_VSick2"),
 };
 
 SurvivorSpeechTable["SSick"] = {
   getText("ContextMenu_speech_SSick1"),
 getText("ContextMenu_speech_SSick2"),
 };
 
   SurvivorSpeechTable["Hungry"] = {
   getText("ContextMenu_speech_Hungry1"),
 getText("ContextMenu_speech_Hungry2"),
 getText("ContextMenu_speech_Hungry3"),
 getText("ContextMenu_speech_Hungry4"),
 getText("ContextMenu_speech_Hungry5"),
 getText("ContextMenu_speech_Hungry6"),
 getText("ContextMenu_speech_Hungry7"),
 getText("ContextMenu_speech_Hungry8"),
 getText("ContextMenu_speech_Hungry9"),
 getText("ContextMenu_speech_Hungry10"),
 };
 

 
 SurvivorSpeechTable["VHungry"] = {
 getText("ContextMenu_speech_VHungry1"),
 getText("ContextMenu_speech_VHungry2"),
 getText("ContextMenu_speech_VHungry3"),
 getText("ContextMenu_speech_VHungry4"),
 getText("ContextMenu_speech_VHungry5"),
  getText("ContextMenu_speech_VHungry6"),
 getText("ContextMenu_speech_VHungry7"),
 getText("ContextMenu_speech_VHungry8"),
 getText("ContextMenu_speech_VHungry9"),
 getText("ContextMenu_speech_VHungry10"),
 };
 

  SurvivorSpeechTable["Starving"] = {
  getText("ContextMenu_speech_Starving1"),
 getText("ContextMenu_speech_Starving2"),
 getText("ContextMenu_speech_Starving3"),
 getText("ContextMenu_speech_Starving4"),
 getText("ContextMenu_speech_Starving5"),
  getText("ContextMenu_speech_Starving6"),
 getText("ContextMenu_speech_Starving7"),
 getText("ContextMenu_speech_Starving8"),
 getText("ContextMenu_speech_Starving9"),
 getText("ContextMenu_speech_Starving10"),
 };

   SurvivorSpeechTable["Roger"] = {
   getText("ContextMenu_speech_Roger1"),
 getText("ContextMenu_speech_Roger2"),
 getText("ContextMenu_speech_Roger3"),
 getText("ContextMenu_speech_Roger4"),
 getText("ContextMenu_speech_Roger5"),
 getText("ContextMenu_speech_Roger6"),
 getText("ContextMenu_speech_Roger7"),
 getText("ContextMenu_speech_Roger8"),
 getText("ContextMenu_speech_Roger9"),
 getText("ContextMenu_speech_Roger10"),
 getText("ContextMenu_speech_Roger11"),
 getText("ContextMenu_speech_Roger12"),
 getText("ContextMenu_speech_Roger13"),
 getText("ContextMenu_speech_Roger14"),
 getText("ContextMenu_speech_Roger15"),
 getText("ContextMenu_speech_Roger16"),
 getText("ContextMenu_speech_Roger17"),
 getText("ContextMenu_speech_Roger18"),
 getText("ContextMenu_speech_Roger19"),
 getText("ContextMenu_speech_Roger20"),
 getText("ContextMenu_speech_Roger21"),
 getText("ContextMenu_speech_Roger22"),
 getText("ContextMenu_speech_Roger23"),
 getText("ContextMenu_speech_Roger24"),
 getText("ContextMenu_speech_Roger25"),
 getText("ContextMenu_speech_Roger26"),
 getText("ContextMenu_speech_Roger27"),
 getText("ContextMenu_speech_Roger28"),
 getText("ContextMenu_speech_Roger29"),
 getText("ContextMenu_speech_Roger30"),
  };
 
    SurvivorSpeechTable["No"] = {
	getText("ContextMenu_speech_No1"),
 getText("ContextMenu_speech_No2"),
 getText("ContextMenu_speech_No3"),
 getText("ContextMenu_speech_No4"),
 getText("ContextMenu_speech_No5"),
 getText("ContextMenu_speech_No6"),
 getText("ContextMenu_speech_No7"),
 getText("ContextMenu_speech_No8"),
 getText("ContextMenu_speech_No9"),
 getText("ContextMenu_speech_No10"),
 getText("ContextMenu_speech_No11"),
 getText("ContextMenu_speech_No12"),
 };
 
 SurvivorSpeechTable["Thanks"] = {
 getText("ContextMenu_speech_Thanks1"),
 getText("ContextMenu_speech_Thanks2"),
 getText("ContextMenu_speech_Thanks3"),
 getText("ContextMenu_speech_Thanks4"),
 getText("ContextMenu_speech_Thanks5"),
 getText("ContextMenu_speech_Thanks6"),
 getText("ContextMenu_speech_Thanks7"),
 getText("ContextMenu_speech_Thanks8"),
 };
 

  SurvivorSpeechTable["HitByPlayer"] = {
  getText("ContextMenu_speech_HitByPlayer1"),
 getText("ContextMenu_speech_HitByPlayer2"),
 getText("ContextMenu_speech_HitByPlayer3"),
 getText("ContextMenu_speech_HitByPlayer4"),
 getText("ContextMenu_speech_HitByPlayer5"),
 getText("ContextMenu_speech_HitByPlayer6"),
 getText("ContextMenu_speech_HitByPlayer7"),
 getText("ContextMenu_speech_HitByPlayer8"),
 getText("ContextMenu_speech_HitByPlayer9"),
 getText("ContextMenu_speech_HitByPlayer10"),
 getText("ContextMenu_speech_HitByPlayer11"),
 getText("ContextMenu_speech_HitByPlayer12"),
 getText("ContextMenu_speech_HitByPlayer13"),
 getText("ContextMenu_speech_HitByPlayer14"),
 getText("ContextMenu_speech_HitByPlayer15"),
 getText("ContextMenu_speech_HitByPlayer16"),
 getText("ContextMenu_speech_HitByPlayer17"),
 getText("ContextMenu_speech_HitByPlayer18"),
 getText("ContextMenu_speech_HitByPlayer19"),
 getText("ContextMenu_speech_HitByPlayer20"),
 getText("ContextMenu_speech_HitByPlayer21"),
 getText("ContextMenu_speech_HitByPlayer22"),
 getText("ContextMenu_speech_HitByPlayer23"),
 getText("ContextMenu_speech_HitByPlayer24"),
 getText("ContextMenu_speech_HitByPlayer25"),
 getText("ContextMenu_speech_HitByPlayer26"),
 getText("ContextMenu_speech_HitByPlayer27"),
 getText("ContextMenu_speech_HitByPlayer28"),
 getText("ContextMenu_speech_HitByPlayer29"),
 };

 
 SurvivorSpeechTable["SeenFirstZombie"] = {
 getText("ContextMenu_speech_SeenFirstZombie1"),
 getText("ContextMenu_speech_SeenFirstZombie2"),
 getText("ContextMenu_speech_SeenFirstZombie3"),
 getText("ContextMenu_speech_SeenFirstZombie4"),
 getText("ContextMenu_speech_SeenFirstZombie5"),
 getText("ContextMenu_speech_SeenFirstZombie6"),
 getText("ContextMenu_speech_SeenFirstZombie7"),
 getText("ContextMenu_speech_SeenFirstZombie8"),
 getText("ContextMenu_speech_SeenFirstZombie9"),
 getText("ContextMenu_speech_SeenFirstZombie10"),
 getText("ContextMenu_speech_SeenFirstZombie11"),
 getText("ContextMenu_speech_SeenFirstZombie12"),
 getText("ContextMenu_speech_SeenFirstZombie13"),
 getText("ContextMenu_speech_SeenFirstZombie14"),
 getText("ContextMenu_speech_SeenFirstZombie15"),
 getText("ContextMenu_speech_SeenFirstZombie16"),
 getText("ContextMenu_speech_SeenFirstZombie17"),
 getText("ContextMenu_speech_SeenFirstZombie18"),
 };
 

  SurvivorSpeechTable["IdleChatter"] = {
 getText("ContextMenu_speech_IdleChatter1"),
 getText("ContextMenu_speech_IdleChatter2"),
 getText("ContextMenu_speech_IdleChatter3"),
 getText("ContextMenu_speech_IdleChatter4"),
 getText("ContextMenu_speech_IdleChatter5"),
 getText("ContextMenu_speech_IdleChatter6"),
 getText("ContextMenu_speech_IdleChatter7"),
 getText("ContextMenu_speech_IdleChatter8"),
 getText("ContextMenu_speech_IdleChatter9"),
 getText("ContextMenu_speech_IdleChatter10"),
 getText("ContextMenu_speech_IdleChatter11"),
 getText("ContextMenu_speech_IdleChatter12"),
 getText("ContextMenu_speech_IdleChatter13"),
 getText("ContextMenu_speech_IdleChatter14"),
 getText("ContextMenu_speech_IdleChatter15"),
 getText("ContextMenu_speech_IdleChatter16"),
 getText("ContextMenu_speech_IdleChatter17"),
 getText("ContextMenu_speech_IdleChatter18"),
 getText("ContextMenu_speech_IdleChatter19"),
 getText("ContextMenu_speech_IdleChatter20"),
 getText("ContextMenu_speech_IdleChatter21"),
 getText("ContextMenu_speech_IdleChatter22"),
 getText("ContextMenu_speech_IdleChatter23"),
 getText("ContextMenu_speech_IdleChatter24"),
 getText("ContextMenu_speech_IdleChatter25"),
 getText("ContextMenu_speech_IdleChatter26"),
 getText("ContextMenu_speech_IdleChatter27"),
 getText("ContextMenu_speech_IdleChatter28"),
 getText("ContextMenu_speech_IdleChatter29"),
 getText("ContextMenu_speech_IdleChatter30"),
 getText("ContextMenu_speech_IdleChatter31"),
 getText("ContextMenu_speech_IdleChatter32"),
 getText("ContextMenu_speech_IdleChatter33"),
 getText("ContextMenu_speech_IdleChatter34"),
 getText("ContextMenu_speech_IdleChatter35"),
 getText("ContextMenu_speech_IdleChatter36"),
 getText("ContextMenu_speech_IdleChatter37"),
 getText("ContextMenu_speech_IdleChatter38"),
 getText("ContextMenu_speech_IdleChatter39"),
 getText("ContextMenu_speech_IdleChatter40"),
 getText("ContextMenu_speech_IdleChatter41"),
 getText("ContextMenu_speech_IdleChatter42"),
 getText("ContextMenu_speech_IdleChatter43"),
 getText("ContextMenu_speech_IdleChatter44"),
 getText("ContextMenu_speech_IdleChatter45"),
 getText("ContextMenu_speech_IdleChatter46"),
 getText("ContextMenu_speech_IdleChatter47"),
 getText("ContextMenu_speech_IdleChatter48"),
 getText("ContextMenu_speech_IdleChatter49"),
 getText("ContextMenu_speech_IdleChatter50"),
 getText("ContextMenu_speech_IdleChatter51"),
 getText("ContextMenu_speech_IdleChatter52"),
 getText("ContextMenu_speech_IdleChatter53"),
 getText("ContextMenu_speech_IdleChatter54"),
 getText("ContextMenu_speech_IdleChatter55"),
 getText("ContextMenu_speech_IdleChatter56"),
 getText("ContextMenu_speech_IdleChatter57"),
 getText("ContextMenu_speech_IdleChatter58"),
 getText("ContextMenu_speech_IdleChatter59"),
 getText("ContextMenu_speech_IdleChatter60"),
 getText("ContextMenu_speech_IdleChatter61"),
 getText("ContextMenu_speech_IdleChatter62"),
 getText("ContextMenu_speech_IdleChatter63"),
 getText("ContextMenu_speech_IdleChatter64"),
 getText("ContextMenu_speech_IdleChatter65"),
 getText("ContextMenu_speech_IdleChatter66"),
 getText("ContextMenu_speech_IdleChatter67"),
 getText("ContextMenu_speech_IdleChatter68"),
 getText("ContextMenu_speech_IdleChatter69"),
 getText("ContextMenu_speech_IdleChatter70"),
 getText("ContextMenu_speech_IdleChatter71"),
 getText("ContextMenu_speech_IdleChatter72"),
 getText("ContextMenu_speech_IdleChatter73"),
 getText("ContextMenu_speech_IdleChatter74"),
 getText("ContextMenu_speech_IdleChatter75"),
 getText("ContextMenu_speech_IdleChatter76"),
 getText("ContextMenu_speech_IdleChatter77"),
 getText("ContextMenu_speech_IdleChatter78"),
 getText("ContextMenu_speech_IdleChatter79"),
 getText("ContextMenu_speech_IdleChatter80"),
 getText("ContextMenu_speech_IdleChatter81"),
 getText("ContextMenu_speech_IdleChatter82"),
 getText("ContextMenu_speech_IdleChatter83"),
 getText("ContextMenu_speech_IdleChatter84"),
 getText("ContextMenu_speech_IdleChatter85"),
 getText("ContextMenu_speech_IdleChatter86"),
 getText("ContextMenu_speech_IdleChatter87"),
 getText("ContextMenu_speech_IdleChatter88"),
 getText("ContextMenu_speech_IdleChatter89"),
 getText("ContextMenu_speech_IdleChatter90"),
 getText("ContextMenu_speech_IdleChatter91"),
 getText("ContextMenu_speech_IdleChatter92"),
 getText("ContextMenu_speech_IdleChatter93"),
 getText("ContextMenu_speech_IdleChatter94"),
 getText("ContextMenu_speech_IdleChatter95"),
 getText("ContextMenu_speech_IdleChatter96"),
 getText("ContextMenu_speech_IdleChatter97"),
 getText("ContextMenu_speech_IdleChatter98"),
 getText("ContextMenu_speech_IdleChatter99"),
 getText("ContextMenu_speech_IdleChatter100"),
 getText("ContextMenu_speech_IdleChatter101"),
 getText("ContextMenu_speech_IdleChatter102"),
 getText("ContextMenu_speech_IdleChatter103"),
 getText("ContextMenu_speech_IdleChatter104"),
 getText("ContextMenu_speech_IdleChatter105"),
 getText("ContextMenu_speech_IdleChatter106"),
 getText("ContextMenu_speech_IdleChatter107"),
 getText("ContextMenu_speech_IdleChatter108"),
 getText("ContextMenu_speech_IdleChatter109"),
 getText("ContextMenu_speech_IdleChatter110"),
 getText("ContextMenu_speech_IdleChatter111"),
 getText("ContextMenu_speech_IdleChatter112"),
 getText("ContextMenu_speech_IdleChatter113"),
 getText("ContextMenu_speech_IdleChatter114"),
 getText("ContextMenu_speech_IdleChatter115"),
 getText("ContextMenu_speech_IdleChatter116"),
 getText("ContextMenu_speech_IdleChatter117"),
 getText("ContextMenu_speech_IdleChatter118"),
 getText("ContextMenu_speech_IdleChatter119"),
 getText("ContextMenu_speech_IdleChatter120"),
 getText("ContextMenu_speech_IdleChatter121"),
 getText("ContextMenu_speech_IdleChatter122"),
 getText("ContextMenu_speech_IdleChatter123"),
 getText("ContextMenu_speech_IdleChatter124"),
 getText("ContextMenu_speech_IdleChatter125"),
 getText("ContextMenu_speech_IdleChatter126"),
 getText("ContextMenu_speech_IdleChatter127"),
 getText("ContextMenu_speech_IdleChatter128"),
 getText("ContextMenu_speech_IdleChatter129"),
 getText("ContextMenu_speech_IdleChatter130"),
 getText("ContextMenu_speech_IdleChatter131"),
 getText("ContextMenu_speech_IdleChatter132"),
 getText("ContextMenu_speech_IdleChatter133"),
 getText("ContextMenu_speech_IdleChatter134"),
 getText("ContextMenu_speech_IdleChatter135"),
 getText("ContextMenu_speech_IdleChatter136"),
 getText("ContextMenu_speech_IdleChatter137"),
 getText("ContextMenu_speech_IdleChatter138"),
 getText("ContextMenu_speech_IdleChatter139"),
 getText("ContextMenu_speech_IdleChatter140"),
 };
 

 SurvivorSpeechTable["PreZombieChatter"] = {
 getText("ContextMenu_speech_PreZombieChatter1"),
 getText("ContextMenu_speech_PreZombieChatter2"),
 getText("ContextMenu_speech_PreZombieChatter3"),
 getText("ContextMenu_speech_PreZombieChatter4"),
 getText("ContextMenu_speech_PreZombieChatter5"),
 getText("ContextMenu_speech_PreZombieChatter6"),
 getText("ContextMenu_speech_PreZombieChatter7"),
 getText("ContextMenu_speech_PreZombieChatter8"),
 getText("ContextMenu_speech_PreZombieChatter9"),
 getText("ContextMenu_speech_PreZombieChatter10"),
 getText("ContextMenu_speech_PreZombieChatter11"),
 getText("ContextMenu_speech_PreZombieChatter12"),
 getText("ContextMenu_speech_PreZombieChatter13"),
 getText("ContextMenu_speech_PreZombieChatter14"),
 };
 

 SurvivorSpeechTable["Hurt"] = {
 getText("ContextMenu_speech_Hurt1"),
getText("ContextMenu_speech_Hurt2"),
getText("ContextMenu_speech_Hurt3"),
getText("ContextMenu_speech_Hurt4"),
getText("ContextMenu_speech_Hurt5"),
getText("ContextMenu_speech_Hurt6"),
getText("ContextMenu_speech_Hurt7"),
getText("ContextMenu_speech_Hurt8"),
getText("ContextMenu_speech_Hurt9"),
getText("ContextMenu_speech_Hurt10"),
getText("ContextMenu_speech_Hurt11"),
getText("ContextMenu_speech_Hurt12"),
getText("ContextMenu_speech_Hurt13"),
getText("ContextMenu_speech_Hurt14"),
getText("ContextMenu_speech_Hurt15"),
getText("ContextMenu_speech_Hurt16"),
getText("ContextMenu_speech_Hurt17"),
getText("ContextMenu_speech_Hurt18"),
};
 

 
SurvivorSpeechTable["Injured"] = {
getText("ContextMenu_speech_Injured1"),
getText("ContextMenu_speech_Injured2"),
getText("ContextMenu_speech_Injured3"),
getText("ContextMenu_speech_Injured4"),
getText("ContextMenu_speech_Injured5"),
getText("ContextMenu_speech_Injured6"),
getText("ContextMenu_speech_Injured7"),
getText("ContextMenu_speech_Injured8"),
getText("ContextMenu_speech_Injured9"),
getText("ContextMenu_speech_Injured10"),
getText("ContextMenu_speech_Injured11"),
getText("ContextMenu_speech_Injured12"),
getText("ContextMenu_speech_Injured13"),
getText("ContextMenu_speech_Injured14"),
getText("ContextMenu_speech_Injured15"),
getText("ContextMenu_speech_Injured16"),
getText("ContextMenu_speech_Injured17"),
getText("ContextMenu_speech_Injured18"),
getText("ContextMenu_speech_Injured19"),
getText("ContextMenu_speech_Injured20"),
};
 

 
SurvivorSpeechTable["BadInjured"] = {
getText("ContextMenu_speech_BadInjured1"),
getText("ContextMenu_speech_BadInjured2"),
getText("ContextMenu_speech_BadInjured3"),
getText("ContextMenu_speech_BadInjured4"),
getText("ContextMenu_speech_BadInjured5"),
getText("ContextMenu_speech_BadInjured6"),
getText("ContextMenu_speech_BadInjured7"),
getText("ContextMenu_speech_BadInjured8"),
getText("ContextMenu_speech_BadInjured9"),
getText("ContextMenu_speech_BadInjured10"),
getText("ContextMenu_speech_BadInjured11"),
getText("ContextMenu_speech_BadInjured12"),
getText("ContextMenu_speech_BadInjured13"),
getText("ContextMenu_speech_BadInjured14"),
getText("ContextMenu_speech_BadInjured15"),
getText("ContextMenu_speech_BadInjured16"),
getText("ContextMenu_speech_BadInjured17"),
};
 

SurvivorSpeechTable["SeriousInjured"] = {
getText("ContextMenu_speech_SeriousInjured1"),
getText("ContextMenu_speech_SeriousInjured2"),
getText("ContextMenu_speech_SeriousInjured3"),
getText("ContextMenu_speech_SeriousInjured4"),
getText("ContextMenu_speech_SeriousInjured5"),
getText("ContextMenu_speech_SeriousInjured6"),
getText("ContextMenu_speech_SeriousInjured7"),
getText("ContextMenu_speech_SeriousInjured8"),
getText("ContextMenu_speech_SeriousInjured9"),
getText("ContextMenu_speech_SeriousInjured10"),
getText("ContextMenu_speech_SeriousInjured11"),
getText("ContextMenu_speech_SeriousInjured12"),
getText("ContextMenu_speech_SeriousInjured13"),
getText("ContextMenu_speech_SeriousInjured14"),
getText("ContextMenu_speech_SeriousInjured15"),
getText("ContextMenu_speech_SeriousInjured16"),
getText("ContextMenu_speech_SeriousInjured17"),
getText("ContextMenu_speech_SeriousInjured18"),
getText("ContextMenu_speech_SeriousInjured19"),
getText("ContextMenu_speech_SeriousInjured20"),
getText("ContextMenu_speech_SeriousInjured21"),
getText("ContextMenu_speech_SeriousInjured22"),
getText("ContextMenu_speech_SeriousInjured23"),
};
 

SurvivorSpeechTable["FatalInjured"] = {
getText("ContextMenu_speech_FatalInjured1"),
getText("ContextMenu_speech_FatalInjured2"),
getText("ContextMenu_speech_FatalInjured3"),
getText("ContextMenu_speech_FatalInjured4"),
getText("ContextMenu_speech_FatalInjured5"),
getText("ContextMenu_speech_FatalInjured6"),
getText("ContextMenu_speech_FatalInjured7"),
getText("ContextMenu_speech_FatalInjured8"),
getText("ContextMenu_speech_FatalInjured9"),
getText("ContextMenu_speech_FatalInjured10"),
getText("ContextMenu_speech_FatalInjured11"),
getText("ContextMenu_speech_FatalInjured12"),
getText("ContextMenu_speech_FatalInjured13"),
getText("ContextMenu_speech_FatalInjured14"),
getText("ContextMenu_speech_FatalInjured15"),
getText("ContextMenu_speech_FatalInjured16"),
getText("ContextMenu_speech_FatalInjured17"),
};
 

SurvivorSpeechTable["FinalWords"] = {
getText("ContextMenu_speech_FinalWords1"),
getText("ContextMenu_speech_FinalWords2"),
getText("ContextMenu_speech_FinalWords3"),
getText("ContextMenu_speech_FinalWords4"),
getText("ContextMenu_speech_FinalWords5"),
getText("ContextMenu_speech_FinalWords6"),
getText("ContextMenu_speech_FinalWords7"),
getText("ContextMenu_speech_FinalWords8"),
getText("ContextMenu_speech_FinalWords9"),
getText("ContextMenu_speech_FinalWords10"),
getText("ContextMenu_speech_FinalWords11"),
getText("ContextMenu_speech_FinalWords12"),
getText("ContextMenu_speech_FinalWords13"),
getText("ContextMenu_speech_FinalWords14"),
getText("ContextMenu_speech_FinalWords15"),
getText("ContextMenu_speech_FinalWords16"),
getText("ContextMenu_speech_FinalWords17"),
getText("ContextMenu_speech_FinalWords18"),
getText("ContextMenu_speech_FinalWords19"),
getText("ContextMenu_speech_FinalWords20"),
getText("ContextMenu_speech_FinalWords21"),
getText("ContextMenu_speech_FinalWords22"),
getText("ContextMenu_speech_FinalWords23"),
getText("ContextMenu_speech_FinalWords24"),
getText("ContextMenu_speech_FinalWords25"),
getText("ContextMenu_speech_FinalWords26"),
getText("ContextMenu_speech_FinalWords27"),
getText("ContextMenu_speech_FinalWords28"),
getText("ContextMenu_speech_FinalWords29"),
getText("ContextMenu_speech_FinalWords30"),
getText("ContextMenu_speech_FinalWords31"),
};
 

 
SurvivorSpeechTable["NameText"] = {
getText("ContextMenu_speech_NameText1"),
getText("ContextMenu_speech_NameText2"),
getText("ContextMenu_speech_NameText3"),
getText("ContextMenu_speech_NameText4"),
getText("ContextMenu_speech_NameText5"),
getText("ContextMenu_speech_NameText6"),
getText("ContextMenu_speech_NameText7"),
getText("ContextMenu_speech_NameText8"),
getText("ContextMenu_speech_NameText9"),
};
 

SurvivorSpeechTable["Greetings"] = {
getText("ContextMenu_speech_Greetings1"),
getText("ContextMenu_speech_Greetings2"),
getText("ContextMenu_speech_Greetings3"),
getText("ContextMenu_speech_Greetings4"),
getText("ContextMenu_speech_Greetings5"),
getText("ContextMenu_speech_Greetings6"),
getText("ContextMenu_speech_Greetings7"),
getText("ContextMenu_speech_Greetings8"),
getText("ContextMenu_speech_Greetings9"),
getText("ContextMenu_speech_Greetings10"),
getText("ContextMenu_speech_Greetings11"),
getText("ContextMenu_speech_Greetings12"),
getText("ContextMenu_speech_Greetings13"),
getText("ContextMenu_speech_Greetings14"),
getText("ContextMenu_speech_Greetings15"),
getText("ContextMenu_speech_Greetings16"),
getText("ContextMenu_speech_Greetings17"),
getText("ContextMenu_speech_Greetings18"),
getText("ContextMenu_speech_Greetings19"),
getText("ContextMenu_speech_Greetings20"),
getText("ContextMenu_speech_Greetings21"),
getText("ContextMenu_speech_Greetings22"),
getText("ContextMenu_speech_Greetings23"),
getText("ContextMenu_speech_Greetings24"),
getText("ContextMenu_speech_Greetings25"),
getText("ContextMenu_speech_Greetings26"),
getText("ContextMenu_speech_Greetings27"),
getText("ContextMenu_speech_Greetings28"),
getText("ContextMenu_speech_Greetings29"),
getText("ContextMenu_speech_Greetings30"),
getText("ContextMenu_speech_Greetings31"),
getText("ContextMenu_speech_Greetings32"),
getText("ContextMenu_speech_Greetings33"),
getText("ContextMenu_speech_Greetings34"),
getText("ContextMenu_speech_Greetings35"),
getText("ContextMenu_speech_Greetings36"),
getText("ContextMenu_speech_Greetings37"),
getText("ContextMenu_speech_Greetings38"),
getText("ContextMenu_speech_Greetings39"),
getText("ContextMenu_speech_Greetings40"),
getText("ContextMenu_speech_Greetings41"),
getText("ContextMenu_speech_Greetings42"),
getText("ContextMenu_speech_Greetings43"),
getText("ContextMenu_speech_Greetings44"),
getText("ContextMenu_speech_Greetings45"),
getText("ContextMenu_speech_Greetings46"),
};
 

SurvivorSpeechTable["WantToHide"] = {
getText("ContextMenu_speech_WantToHide1"),
getText("ContextMenu_speech_WantToHide2"),
getText("ContextMenu_speech_WantToHide3"),
getText("ContextMenu_speech_WantToHide4"),
getText("ContextMenu_speech_WantToHide5"),
getText("ContextMenu_speech_WantToHide6"),
getText("ContextMenu_speech_WantToHide7"),
getText("ContextMenu_speech_WantToHide8"),
getText("ContextMenu_speech_WantToHide9"),
getText("ContextMenu_speech_WantToHide10"),
getText("ContextMenu_speech_WantToHide11"),
getText("ContextMenu_speech_WantToHide12"),
getText("ContextMenu_speech_WantToHide13"),
getText("ContextMenu_speech_WantToHide14"),
getText("ContextMenu_speech_WantToHide15"),
getText("ContextMenu_speech_WantToHide16"),
getText("ContextMenu_speech_WantToHide17"),
getText("ContextMenu_speech_WantToHide18"),
getText("ContextMenu_speech_WantToHide19"),
getText("ContextMenu_speech_WantToHide20"),
getText("ContextMenu_speech_WantToHide21"),
getText("ContextMenu_speech_WantToHide22"),
getText("ContextMenu_speech_WantToHide23"),
};
 

 
SurvivorSpeechTable["FoundHidingPlace"] = {
getText("ContextMenu_speech_FoundHidingPlace1"),
getText("ContextMenu_speech_FoundHidingPlace2"),
getText("ContextMenu_speech_FoundHidingPlace3"),
getText("ContextMenu_speech_FoundHidingPlace4"),
getText("ContextMenu_speech_FoundHidingPlace5"),
getText("ContextMenu_speech_FoundHidingPlace6"),
getText("ContextMenu_speech_FoundHidingPlace7"),
getText("ContextMenu_speech_FoundHidingPlace8"),
getText("ContextMenu_speech_FoundHidingPlace9"),
getText("ContextMenu_speech_FoundHidingPlace10"),
getText("ContextMenu_speech_FoundHidingPlace11"),
getText("ContextMenu_speech_FoundHidingPlace12"),
getText("ContextMenu_speech_FoundHidingPlace13"),
getText("ContextMenu_speech_FoundHidingPlace14"),
getText("ContextMenu_speech_FoundHidingPlace15"),
getText("ContextMenu_speech_FoundHidingPlace16"),
getText("ContextMenu_speech_FoundHidingPlace17"),
getText("ContextMenu_speech_FoundHidingPlace18"),
getText("ContextMenu_speech_FoundHidingPlace19"),
getText("ContextMenu_speech_FoundHidingPlace20"),
getText("ContextMenu_speech_FoundHidingPlace21"),
getText("ContextMenu_speech_FoundHidingPlace22"),
getText("ContextMenu_speech_FoundHidingPlace23"),
getText("ContextMenu_speech_FoundHidingPlace24"),
getText("ContextMenu_speech_FoundHidingPlace25"),
getText("ContextMenu_speech_FoundHidingPlace26"),
getText("ContextMenu_speech_FoundHidingPlace27"),
getText("ContextMenu_speech_FoundHidingPlace28"),
getText("ContextMenu_speech_FoundHidingPlace29"),
getText("ContextMenu_speech_FoundHidingPlace30"),
getText("ContextMenu_speech_FoundHidingPlace31"),
getText("ContextMenu_speech_FoundHidingPlace32"),
getText("ContextMenu_speech_FoundHidingPlace33"),
getText("ContextMenu_speech_FoundHidingPlace34"),
getText("ContextMenu_speech_FoundHidingPlace35"),
getText("ContextMenu_speech_FoundHidingPlace36"),
getText("ContextMenu_speech_FoundHidingPlace37"),
getText("ContextMenu_speech_FoundHidingPlace38"),
getText("ContextMenu_speech_FoundHidingPlace39"),
getText("ContextMenu_speech_FoundHidingPlace40"),
getText("ContextMenu_speech_FoundHidingPlace41"),
};
 

SurvivorSpeechTable["NoWhereToHide"] = {
getText("ContextMenu_speech_NoWhereToHide1"),
getText("ContextMenu_speech_NoWhereToHide2"),
getText("ContextMenu_speech_NoWhereToHide3"),
getText("ContextMenu_speech_NoWhereToHide4"),
getText("ContextMenu_speech_NoWhereToHide5"),
getText("ContextMenu_speech_NoWhereToHide6"),
getText("ContextMenu_speech_NoWhereToHide7"),
getText("ContextMenu_speech_NoWhereToHide8"),
getText("ContextMenu_speech_NoWhereToHide9"),
getText("ContextMenu_speech_NoWhereToHide10"),
getText("ContextMenu_speech_NoWhereToHide11"),
getText("ContextMenu_speech_NoWhereToHide12"),
getText("ContextMenu_speech_NoWhereToHide13"),
getText("ContextMenu_speech_NoWhereToHide14"),
getText("ContextMenu_speech_NoWhereToHide15"),
getText("ContextMenu_speech_NoWhereToHide16"),
getText("ContextMenu_speech_NoWhereToHide17"),
getText("ContextMenu_speech_NoWhereToHide18"),
getText("ContextMenu_speech_NoWhereToHide19"),
getText("ContextMenu_speech_NoWhereToHide20"),
getText("ContextMenu_speech_NoWhereToHide21"),
getText("ContextMenu_speech_NoWhereToHide22"),
getText("ContextMenu_speech_NoWhereToHide23"),
};
 

SurvivorSpeechTable["Panic"] = {
getText("ContextMenu_speech_Panic1"),
getText("ContextMenu_speech_Panic2"),
getText("ContextMenu_speech_Panic3"),
getText("ContextMenu_speech_Panic4"),
getText("ContextMenu_speech_Panic5"),
getText("ContextMenu_speech_Panic6"),
getText("ContextMenu_speech_Panic7"),
getText("ContextMenu_speech_Panic8"),
getText("ContextMenu_speech_Panic9"),
getText("ContextMenu_speech_Panic10"),
getText("ContextMenu_speech_Panic11"),
getText("ContextMenu_speech_Panic12"),
getText("ContextMenu_speech_Panic13"),
getText("ContextMenu_speech_Panic14"),
getText("ContextMenu_speech_Panic15"),
getText("ContextMenu_speech_Panic16"),
getText("ContextMenu_speech_Panic17"),
getText("ContextMenu_speech_Panic18"),
getText("ContextMenu_speech_Panic19"),
getText("ContextMenu_speech_Panic20"),
getText("ContextMenu_speech_Panic21"),
getText("ContextMenu_speech_Panic22"),
getText("ContextMenu_speech_Panic23"),
};
 

SurvivorSpeechTable["Scared"] = {
getText("ContextMenu_speech_Scared1"),
getText("ContextMenu_speech_Scared2"),
getText("ContextMenu_speech_Scared3"),
getText("ContextMenu_speech_Scared4"),
getText("ContextMenu_speech_Scared5"),
getText("ContextMenu_speech_Scared6"),
getText("ContextMenu_speech_Scared7"),
getText("ContextMenu_speech_Scared8"),
getText("ContextMenu_speech_Scared9"),
getText("ContextMenu_speech_Scared10"),
getText("ContextMenu_speech_Scared11"),
getText("ContextMenu_speech_Scared12"),
getText("ContextMenu_speech_Scared13"),
getText("ContextMenu_speech_Scared14"),
getText("ContextMenu_speech_Scared15"),
getText("ContextMenu_speech_Scared16"),
getText("ContextMenu_speech_Scared17"),
getText("ContextMenu_speech_Scared18"),
getText("ContextMenu_speech_Scared19"),
getText("ContextMenu_speech_Scared20"),
};
 

SurvivorSpeechTable["Screem"] = {
getText("ContextMenu_speech_Screem1"),
getText("ContextMenu_speech_Screem2"),
getText("ContextMenu_speech_Screem3"),
getText("ContextMenu_speech_Screem4"),
getText("ContextMenu_speech_Screem5"),
getText("ContextMenu_speech_Screem6"),
getText("ContextMenu_speech_Screem7"),
getText("ContextMenu_speech_Screem8"),
getText("ContextMenu_speech_Screem9"),
getText("ContextMenu_speech_Screem10"),
getText("ContextMenu_speech_Screem11"),
getText("ContextMenu_speech_Screem12"),
getText("ContextMenu_speech_Screem13"),
getText("ContextMenu_speech_Screem14"),
getText("ContextMenu_speech_Screem15"),
getText("ContextMenu_speech_Screem16"),
getText("ContextMenu_speech_Screem17"),
getText("ContextMenu_speech_Screem18"),
getText("ContextMenu_speech_Screem19"),
getText("ContextMenu_speech_Screem20"),
getText("ContextMenu_speech_Screem21"),
getText("ContextMenu_speech_Screem22"),
getText("ContextMenu_speech_Screem23"),
};
 

 
 SurvivorSpeechTable["Attack"] = {
 getText("ContextMenu_speech_Attack1"),
getText("ContextMenu_speech_Attack2"),
getText("ContextMenu_speech_Attack3"),
getText("ContextMenu_speech_Attack4"),
getText("ContextMenu_speech_Attack5"),
getText("ContextMenu_speech_Attack6"),
getText("ContextMenu_speech_Attack7"),
getText("ContextMenu_speech_Attack8"),
getText("ContextMenu_speech_Attack9"),
getText("ContextMenu_speech_Attack10"),
getText("ContextMenu_speech_Attack11"),
getText("ContextMenu_speech_Attack12"),
getText("ContextMenu_speech_Attack13"),
getText("ContextMenu_speech_Attack14"),
getText("ContextMenu_speech_Attack15"),
getText("ContextMenu_speech_Attack16"),
getText("ContextMenu_speech_Attack17"),
getText("ContextMenu_speech_Attack18"),
getText("ContextMenu_speech_Attack19"),
getText("ContextMenu_speech_Attack20"),
getText("ContextMenu_speech_Attack21"),
getText("ContextMenu_speech_Attack22"),
getText("ContextMenu_speech_Attack23"),
getText("ContextMenu_speech_Attack24"),
getText("ContextMenu_speech_Attack25"),
getText("ContextMenu_speech_Attack26"),
getText("ContextMenu_speech_Attack27"),
getText("ContextMenu_speech_Attack28"),
getText("ContextMenu_speech_Attack29"),
getText("ContextMenu_speech_Attack30"),
getText("ContextMenu_speech_Attack31"),
getText("ContextMenu_speech_Attack32"),
getText("ContextMenu_speech_Attack33"),
getText("ContextMenu_speech_Attack34"),
getText("ContextMenu_speech_Attack35"),
getText("ContextMenu_speech_Attack36"),
getText("ContextMenu_speech_Attack37"),
getText("ContextMenu_speech_Attack38"),
};

 
 SurvivorSpeechTable["AttackS"] = {
 getText("ContextMenu_speech_AttackS1"),
getText("ContextMenu_speech_AttackS2"),
getText("ContextMenu_speech_AttackS3"),
getText("ContextMenu_speech_AttackS4"),
getText("ContextMenu_speech_AttackS5"),
getText("ContextMenu_speech_AttackS6"),
getText("ContextMenu_speech_AttackS7"),
getText("ContextMenu_speech_AttackS8"),
getText("ContextMenu_speech_AttackS9"),
getText("ContextMenu_speech_AttackS10"),
getText("ContextMenu_speech_AttackS11"),
getText("ContextMenu_speech_AttackS12"),
getText("ContextMenu_speech_AttackS13"),
getText("ContextMenu_speech_AttackS14"),
getText("ContextMenu_speech_AttackS15"),
getText("ContextMenu_speech_AttackS16"),
getText("ContextMenu_speech_AttackS17"),
getText("ContextMenu_speech_AttackS18"),
getText("ContextMenu_speech_AttackS19"),
getText("ContextMenu_speech_AttackS20"),
getText("ContextMenu_speech_AttackS21"),
getText("ContextMenu_speech_AttackS22"),
getText("ContextMenu_speech_AttackS23"),
getText("ContextMenu_speech_AttackS24"),
getText("ContextMenu_speech_AttackS25"),
getText("ContextMenu_speech_AttackS26"),
getText("ContextMenu_speech_AttackS27"),
getText("ContextMenu_speech_AttackS28"),
getText("ContextMenu_speech_AttackS29"),
};
 

SurvivorSpeechTable["Traitor"] = {
getText("ContextMenu_speech_Traitor1"),
getText("ContextMenu_speech_Traitor2"),
getText("ContextMenu_speech_Traitor3"),
getText("ContextMenu_speech_Traitor4"),
getText("ContextMenu_speech_Traitor5"),
getText("ContextMenu_speech_Traitor6"),
getText("ContextMenu_speech_Traitor7"),
getText("ContextMenu_speech_Traitor8"),
getText("ContextMenu_speech_Traitor9"),
getText("ContextMenu_speech_Traitor10"),
getText("ContextMenu_speech_Traitor11"),
getText("ContextMenu_speech_Traitor12"),
getText("ContextMenu_speech_Traitor13"),
getText("ContextMenu_speech_Traitor14"),
getText("ContextMenu_speech_Traitor15"),
getText("ContextMenu_speech_Traitor16"),
getText("ContextMenu_speech_Traitor17"),
getText("ContextMenu_speech_Traitor18"),
getText("ContextMenu_speech_Traitor19"),
getText("ContextMenu_speech_Traitor20"),
getText("ContextMenu_speech_Traitor21"),
getText("ContextMenu_speech_Traitor22"),
};
 

SurvivorSpeechTable["LookingForZombie"] = {
getText("ContextMenu_speech_LookingForZombie1"),
getText("ContextMenu_speech_LookingForZombie2"),
getText("ContextMenu_speech_LookingForZombie3"),
getText("ContextMenu_speech_LookingForZombie4"),
getText("ContextMenu_speech_LookingForZombie5"),
getText("ContextMenu_speech_LookingForZombie6"),
getText("ContextMenu_speech_LookingForZombie7"),
getText("ContextMenu_speech_LookingForZombie8"),
getText("ContextMenu_speech_LookingForZombie9"),
getText("ContextMenu_speech_LookingForZombie10"),
getText("ContextMenu_speech_LookingForZombie11"),
getText("ContextMenu_speech_LookingForZombie12"),
getText("ContextMenu_speech_LookingForZombie13"),
getText("ContextMenu_speech_LookingForZombie14"),
getText("ContextMenu_speech_LookingForZombie15"),
};
 

SurvivorSpeechTable["FoundSurvivor"] = {
getText("ContextMenu_speech_FoundSurvivor1"),
getText("ContextMenu_speech_FoundSurvivor2"),
getText("ContextMenu_speech_FoundSurvivor3"),
getText("ContextMenu_speech_FoundSurvivor4"),
getText("ContextMenu_speech_FoundSurvivor5"),
getText("ContextMenu_speech_FoundSurvivor6"),
getText("ContextMenu_speech_FoundSurvivor7"),
getText("ContextMenu_speech_FoundSurvivor8"),
getText("ContextMenu_speech_FoundSurvivor9"),
getText("ContextMenu_speech_FoundSurvivor10"),
getText("ContextMenu_speech_FoundSurvivor11"),
getText("ContextMenu_speech_FoundSurvivor12"),
getText("ContextMenu_speech_FoundSurvivor13"),
getText("ContextMenu_speech_FoundSurvivor14"),
getText("ContextMenu_speech_FoundSurvivor15"),
getText("ContextMenu_speech_FoundSurvivor16"),
getText("ContextMenu_speech_FoundSurvivor17"),
getText("ContextMenu_speech_FoundSurvivor18"),
getText("ContextMenu_speech_FoundSurvivor19"),
getText("ContextMenu_speech_FoundSurvivor20"),
getText("ContextMenu_speech_FoundSurvivor21"),
getText("ContextMenu_speech_FoundSurvivor22"),
getText("ContextMenu_speech_FoundSurvivor23"),
getText("ContextMenu_speech_FoundSurvivor24"),
getText("ContextMenu_speech_FoundSurvivor25"),
getText("ContextMenu_speech_FoundSurvivor26"),
getText("ContextMenu_speech_FoundSurvivor27"),
getText("ContextMenu_speech_FoundSurvivor28"),
getText("ContextMenu_speech_FoundSurvivor29"),
getText("ContextMenu_speech_FoundSurvivor30"),
getText("ContextMenu_speech_FoundSurvivor31"),
getText("ContextMenu_speech_FoundSurvivor32"),
getText("ContextMenu_speech_FoundSurvivor33"),
getText("ContextMenu_speech_FoundSurvivor34"),
};
 

SurvivorSpeechTable["FoundZombie"] = {
getText("ContextMenu_speech_FoundZombie1"),
getText("ContextMenu_speech_FoundZombie2"),
getText("ContextMenu_speech_FoundZombie3"),
getText("ContextMenu_speech_FoundZombie4"),
getText("ContextMenu_speech_FoundZombie5"),
getText("ContextMenu_speech_FoundZombie6"),
getText("ContextMenu_speech_FoundZombie7"),
getText("ContextMenu_speech_FoundZombie8"),
getText("ContextMenu_speech_FoundZombie9"),
getText("ContextMenu_speech_FoundZombie10"),
getText("ContextMenu_speech_FoundZombie11"),
getText("ContextMenu_speech_FoundZombie12"),
getText("ContextMenu_speech_FoundZombie13"),
getText("ContextMenu_speech_FoundZombie14"),
getText("ContextMenu_speech_FoundZombie15"),
getText("ContextMenu_speech_FoundZombie16"),
getText("ContextMenu_speech_FoundZombie17"),
getText("ContextMenu_speech_FoundZombie18"),
getText("ContextMenu_speech_FoundZombie19"),
};
 

 
---  Below is hundreds of girl names and boy names. you dont need to translate them if you don't want to. translate as in, replace them with common names in area of language or change to your phonetic alphabeht. if you do. know that there does not need to be this many. you could just do like 50 of each.
 
SurvivorSpeechTable["GirlNames"] = {
getText("ContextMenu_Names1"),
getText("ContextMenu_Names2"),
getText("ContextMenu_Names3"),
getText("ContextMenu_Names4"),
getText("ContextMenu_Names5"),
getText("ContextMenu_Names6"),
getText("ContextMenu_Names7"),
getText("ContextMenu_Names8"),
getText("ContextMenu_Names9"),
getText("ContextMenu_Names10"),
getText("ContextMenu_Names11"),
getText("ContextMenu_Names12"),
getText("ContextMenu_Names13"),
getText("ContextMenu_Names14"),
getText("ContextMenu_Names15"),
getText("ContextMenu_Names16"),
getText("ContextMenu_Names17"),
getText("ContextMenu_Names18"),
getText("ContextMenu_Names19"),
getText("ContextMenu_Names20"),
getText("ContextMenu_Names21"),
getText("ContextMenu_Names22"),
getText("ContextMenu_Names23"),
getText("ContextMenu_Names24"),
getText("ContextMenu_Names25"),
getText("ContextMenu_Names26"),
getText("ContextMenu_Names27"),
getText("ContextMenu_Names28"),
getText("ContextMenu_Names29"),
getText("ContextMenu_Names30"),
getText("ContextMenu_Names31"),
getText("ContextMenu_Names32"),
getText("ContextMenu_Names33"),
getText("ContextMenu_Names34"),
getText("ContextMenu_Names35"),
getText("ContextMenu_Names36"),
getText("ContextMenu_Names37"),
getText("ContextMenu_Names38"),
getText("ContextMenu_Names39"),
getText("ContextMenu_Names40"),
getText("ContextMenu_Names41"),
getText("ContextMenu_Names42"),
getText("ContextMenu_Names43"),
getText("ContextMenu_Names44"),
getText("ContextMenu_Names45"),
getText("ContextMenu_Names46"),
getText("ContextMenu_Names47"),
getText("ContextMenu_Names48"),
getText("ContextMenu_Names49"),
getText("ContextMenu_Names50"),
getText("ContextMenu_Names51"),
getText("ContextMenu_Names52"),
getText("ContextMenu_Names53"),
getText("ContextMenu_Names54"),
getText("ContextMenu_Names55"),
getText("ContextMenu_Names56"),
getText("ContextMenu_Names57"),
getText("ContextMenu_Names58"),
getText("ContextMenu_Names59"),
getText("ContextMenu_Names60"),
getText("ContextMenu_Names61"),
getText("ContextMenu_Names62"),
getText("ContextMenu_Names63"),
getText("ContextMenu_Names64"),
getText("ContextMenu_Names65"),
getText("ContextMenu_Names66"),
getText("ContextMenu_Names67"),
getText("ContextMenu_Names68"),
getText("ContextMenu_Names69"),
getText("ContextMenu_Names70"),
getText("ContextMenu_Names71"),
getText("ContextMenu_Names72"),
getText("ContextMenu_Names73"),
getText("ContextMenu_Names74"),
getText("ContextMenu_Names75"),
getText("ContextMenu_Names76"),
getText("ContextMenu_Names77"),
getText("ContextMenu_Names78"),
getText("ContextMenu_Names79"),
getText("ContextMenu_Names80"),
getText("ContextMenu_Names81"),
getText("ContextMenu_Names82"),
getText("ContextMenu_Names83"),
getText("ContextMenu_Names84"),
getText("ContextMenu_Names85"),
getText("ContextMenu_Names86"),
getText("ContextMenu_Names87"),
getText("ContextMenu_Names88"),
getText("ContextMenu_Names89"),
getText("ContextMenu_Names90"),
getText("ContextMenu_Names91"),
getText("ContextMenu_Names92"),
getText("ContextMenu_Names93"),
getText("ContextMenu_Names94"),
getText("ContextMenu_Names95"),
getText("ContextMenu_Names96"),
getText("ContextMenu_Names97"),
getText("ContextMenu_Names98"),
getText("ContextMenu_Names99"),
getText("ContextMenu_Names100"),
getText("ContextMenu_Names101"),
getText("ContextMenu_Names102"),
getText("ContextMenu_Names103"),
getText("ContextMenu_Names104"),
getText("ContextMenu_Names105"),
getText("ContextMenu_Names106"),
getText("ContextMenu_Names107"),
getText("ContextMenu_Names108"),
getText("ContextMenu_Names109"),
getText("ContextMenu_Names110"),
getText("ContextMenu_Names111"),
getText("ContextMenu_Names112"),
getText("ContextMenu_Names113"),
getText("ContextMenu_Names114"),
getText("ContextMenu_Names115"),
getText("ContextMenu_Names116"),
getText("ContextMenu_Names117"),
getText("ContextMenu_Names118"),
getText("ContextMenu_Names119"),
getText("ContextMenu_Names120"),
getText("ContextMenu_Names121"),
getText("ContextMenu_Names122"),
getText("ContextMenu_Names123"),
getText("ContextMenu_Names124"),
getText("ContextMenu_Names125"),
getText("ContextMenu_Names126"),
getText("ContextMenu_Names127"),
getText("ContextMenu_Names128"),
getText("ContextMenu_Names129"),
getText("ContextMenu_Names130"),
getText("ContextMenu_Names131"),
getText("ContextMenu_Names132"),
getText("ContextMenu_Names133"),
getText("ContextMenu_Names134"),
getText("ContextMenu_Names135"),
getText("ContextMenu_Names136"),
getText("ContextMenu_Names137"),
getText("ContextMenu_Names138"),
getText("ContextMenu_Names139"),
getText("ContextMenu_Names140"),
getText("ContextMenu_Names141"),
getText("ContextMenu_Names142"),
getText("ContextMenu_Names143"),
getText("ContextMenu_Names144"),
getText("ContextMenu_Names145"),
getText("ContextMenu_Names146"),
getText("ContextMenu_Names147"),
getText("ContextMenu_Names148"),
getText("ContextMenu_Names149"),
getText("ContextMenu_Names150"),
getText("ContextMenu_Names151"),
getText("ContextMenu_Names152"),
getText("ContextMenu_Names153"),
getText("ContextMenu_Names154"),
getText("ContextMenu_Names155"),
getText("ContextMenu_Names156"),
getText("ContextMenu_Names157"),
getText("ContextMenu_Names158"),
getText("ContextMenu_Names159"),
getText("ContextMenu_Names160"),
getText("ContextMenu_Names161"),
getText("ContextMenu_Names162"),
getText("ContextMenu_Names163"),
getText("ContextMenu_Names164"),
getText("ContextMenu_Names165"),
getText("ContextMenu_Names166"),
getText("ContextMenu_Names167"),
getText("ContextMenu_Names168"),
getText("ContextMenu_Names169"),
getText("ContextMenu_Names170"),
getText("ContextMenu_Names171"),
getText("ContextMenu_Names172"),
getText("ContextMenu_Names173"),
getText("ContextMenu_Names174"),
getText("ContextMenu_Names175"),
getText("ContextMenu_Names176"),
getText("ContextMenu_Names177"),
getText("ContextMenu_Names178"),
getText("ContextMenu_Names179"),
getText("ContextMenu_Names180"),
getText("ContextMenu_Names181"),
getText("ContextMenu_Names182"),
getText("ContextMenu_Names183"),
getText("ContextMenu_Names184"),
getText("ContextMenu_Names185"),
getText("ContextMenu_Names186"),
getText("ContextMenu_Names187"),
getText("ContextMenu_Names188"),
getText("ContextMenu_Names189"),
getText("ContextMenu_Names190"),
getText("ContextMenu_Names191"),
getText("ContextMenu_Names192"),
getText("ContextMenu_Names193"),
getText("ContextMenu_Names194"),
getText("ContextMenu_Names195"),
getText("ContextMenu_Names196"),
getText("ContextMenu_Names197"),
getText("ContextMenu_Names198"),
getText("ContextMenu_Names199"),
getText("ContextMenu_Names200"),
getText("ContextMenu_Names201"),
getText("ContextMenu_Names202"),
getText("ContextMenu_Names203"),
getText("ContextMenu_Names204"),
getText("ContextMenu_Names205"),
getText("ContextMenu_Names206"),
getText("ContextMenu_Names207"),
getText("ContextMenu_Names208"),
getText("ContextMenu_Names209"),
getText("ContextMenu_Names210"),
getText("ContextMenu_Names211"),
getText("ContextMenu_Names212"),
getText("ContextMenu_Names213"),
getText("ContextMenu_Names214"),
getText("ContextMenu_Names215"),
getText("ContextMenu_Names216"),
getText("ContextMenu_Names217"),
getText("ContextMenu_Names218"),
getText("ContextMenu_Names219"),
getText("ContextMenu_Names220"),
getText("ContextMenu_Names221"),
getText("ContextMenu_Names222"),
getText("ContextMenu_Names223"),
getText("ContextMenu_Names224"),
getText("ContextMenu_Names225"),
getText("ContextMenu_Names226"),
getText("ContextMenu_Names227"),
getText("ContextMenu_Names228"),
getText("ContextMenu_Names229"),
getText("ContextMenu_Names230"),
getText("ContextMenu_Names231"),
getText("ContextMenu_Names232"),
getText("ContextMenu_Names233"),
getText("ContextMenu_Names234"),
getText("ContextMenu_Names235"),
getText("ContextMenu_Names236"),
getText("ContextMenu_Names237"),
getText("ContextMenu_Names238"),
getText("ContextMenu_Names239"),
getText("ContextMenu_Names240"),
getText("ContextMenu_Names241"),
getText("ContextMenu_Names242"),
getText("ContextMenu_Names243"),
getText("ContextMenu_Names244"),
getText("ContextMenu_Names245"),
getText("ContextMenu_Names246"),
getText("ContextMenu_Names247"),
getText("ContextMenu_Names248"),
getText("ContextMenu_Names249"),
getText("ContextMenu_Names250"),
getText("ContextMenu_Names251"),
getText("ContextMenu_Names252"),
getText("ContextMenu_Names253"),
getText("ContextMenu_Names254"),
getText("ContextMenu_Names255"),
getText("ContextMenu_Names256"),
getText("ContextMenu_Names257"),
getText("ContextMenu_Names258"),
getText("ContextMenu_Names259"),
getText("ContextMenu_Names260"),
getText("ContextMenu_Names261"),
getText("ContextMenu_Names262"),
getText("ContextMenu_Names263"),
getText("ContextMenu_Names264"),
getText("ContextMenu_Names265"),
getText("ContextMenu_Names266"),
getText("ContextMenu_Names267"),
getText("ContextMenu_Names268"),
getText("ContextMenu_Names269"),
getText("ContextMenu_Names270"),
getText("ContextMenu_Names271"),
getText("ContextMenu_Names272"),
getText("ContextMenu_Names273"),
getText("ContextMenu_Names274"),
getText("ContextMenu_Names275"),
getText("ContextMenu_Names276"),
getText("ContextMenu_Names277"),
getText("ContextMenu_Names278"),
getText("ContextMenu_Names279"),
getText("ContextMenu_Names280"),
getText("ContextMenu_Names281"),
getText("ContextMenu_Names282"),
getText("ContextMenu_Names283"),
getText("ContextMenu_Names284"),
getText("ContextMenu_Names285"),
getText("ContextMenu_Names286"),
getText("ContextMenu_Names287"),
getText("ContextMenu_Names288"),
getText("ContextMenu_Names289"),
getText("ContextMenu_Names290"),
getText("ContextMenu_Names291"),
getText("ContextMenu_Names292"),
getText("ContextMenu_Names293"),
getText("ContextMenu_Names294"),
getText("ContextMenu_Names295"),
getText("ContextMenu_Names296"),
getText("ContextMenu_Names297"),
getText("ContextMenu_Names298"),
getText("ContextMenu_Names299"),
getText("ContextMenu_Names300"),
getText("ContextMenu_Names301"),
getText("ContextMenu_Names302"),
getText("ContextMenu_Names303"),
getText("ContextMenu_Names304"),
getText("ContextMenu_Names305"),
getText("ContextMenu_Names306"),
getText("ContextMenu_Names307"),
getText("ContextMenu_Names308"),
getText("ContextMenu_Names309"),
getText("ContextMenu_Names310"),
getText("ContextMenu_Names311"),
getText("ContextMenu_Names312"),
getText("ContextMenu_Names313"),
getText("ContextMenu_Names314"),
getText("ContextMenu_Names315"),
getText("ContextMenu_Names316"),
getText("ContextMenu_Names317"),
getText("ContextMenu_Names318"),
getText("ContextMenu_Names319"),
getText("ContextMenu_Names320"),
getText("ContextMenu_Names321"),
getText("ContextMenu_Names322"),
getText("ContextMenu_Names323"),
getText("ContextMenu_Names324"),
getText("ContextMenu_Names325"),
getText("ContextMenu_Names326"),
getText("ContextMenu_Names327"),
getText("ContextMenu_Names328"),
getText("ContextMenu_Names329"),
getText("ContextMenu_Names330"),
getText("ContextMenu_Names331"),
getText("ContextMenu_Names332"),
getText("ContextMenu_Names333"),
getText("ContextMenu_Names334"),
getText("ContextMenu_Names335"),
getText("ContextMenu_Names336"),
getText("ContextMenu_Names337"),
getText("ContextMenu_Names338"),
getText("ContextMenu_Names339"),
getText("ContextMenu_Names340"),
getText("ContextMenu_Names341"),
getText("ContextMenu_Names342"),
getText("ContextMenu_Names343"),
getText("ContextMenu_Names344"),
getText("ContextMenu_Names345"),
getText("ContextMenu_Names346"),
getText("ContextMenu_Names347"),
getText("ContextMenu_Names348"),
getText("ContextMenu_Names349"),
getText("ContextMenu_Names350"),
getText("ContextMenu_Names351"),
getText("ContextMenu_Names352"),
getText("ContextMenu_Names353"),
getText("ContextMenu_Names354"),
getText("ContextMenu_Names355"),
getText("ContextMenu_Names356"),
getText("ContextMenu_Names357"),
getText("ContextMenu_Names358"),
getText("ContextMenu_Names359"),
getText("ContextMenu_Names360"),
getText("ContextMenu_Names361"),
getText("ContextMenu_Names362"),
getText("ContextMenu_Names363"),
getText("ContextMenu_Names364"),
getText("ContextMenu_Names365"),
getText("ContextMenu_Names366"),
getText("ContextMenu_Names367"),
getText("ContextMenu_Names368"),
getText("ContextMenu_Names369"),
getText("ContextMenu_Names370"),
getText("ContextMenu_Names371"),
getText("ContextMenu_Names372"),
getText("ContextMenu_Names373"),
getText("ContextMenu_Names374"),
getText("ContextMenu_Names375"),
getText("ContextMenu_Names376"),
getText("ContextMenu_Names377"),
getText("ContextMenu_Names378"),
getText("ContextMenu_Names379"),
getText("ContextMenu_Names380"),
getText("ContextMenu_Names381"),
getText("ContextMenu_Names382"),
getText("ContextMenu_Names383"),
getText("ContextMenu_Names384"),
getText("ContextMenu_Names385"),
getText("ContextMenu_Names386"),
getText("ContextMenu_Names387"),
getText("ContextMenu_Names388"),
getText("ContextMenu_Names389"),
getText("ContextMenu_Names390"),
getText("ContextMenu_Names391"),
getText("ContextMenu_Names392"),
getText("ContextMenu_Names393"),
getText("ContextMenu_Names394"),
getText("ContextMenu_Names395"),
getText("ContextMenu_Names396"),
getText("ContextMenu_Names397"),
getText("ContextMenu_Names398"),
getText("ContextMenu_Names399"),
getText("ContextMenu_Names400"),
getText("ContextMenu_Names401"),
getText("ContextMenu_Names402"),
getText("ContextMenu_Names403"),
getText("ContextMenu_Names404"),
getText("ContextMenu_Names405"),
getText("ContextMenu_Names406"),
getText("ContextMenu_Names407"),
getText("ContextMenu_Names408"),
getText("ContextMenu_Names409"),
getText("ContextMenu_Names410"),
getText("ContextMenu_Names411"),
getText("ContextMenu_Names412"),
getText("ContextMenu_Names413"),
getText("ContextMenu_Names414"),
getText("ContextMenu_Names415"),
getText("ContextMenu_Names416"),
getText("ContextMenu_Names417"),
getText("ContextMenu_Names418"),
getText("ContextMenu_Names419"),
getText("ContextMenu_Names420"),
getText("ContextMenu_Names421"),
getText("ContextMenu_Names422"),
getText("ContextMenu_Names423"),
getText("ContextMenu_Names424"),
getText("ContextMenu_Names425"),
getText("ContextMenu_Names426"),
getText("ContextMenu_Names427"),
getText("ContextMenu_Names428"),
getText("ContextMenu_Names429"),
getText("ContextMenu_Names430"),
getText("ContextMenu_Names431"),
getText("ContextMenu_Names432"),
getText("ContextMenu_Names433"),
getText("ContextMenu_Names434"),
getText("ContextMenu_Names435"),
getText("ContextMenu_Names436"),
getText("ContextMenu_Names437"),
getText("ContextMenu_Names438"),
getText("ContextMenu_Names439"),
getText("ContextMenu_Names440"),
getText("ContextMenu_Names441"),
getText("ContextMenu_Names442"),
getText("ContextMenu_Names443"),
getText("ContextMenu_Names444"),
getText("ContextMenu_Names445"),
getText("ContextMenu_Names446"),
getText("ContextMenu_Names447"),
getText("ContextMenu_Names448"),
getText("ContextMenu_Names449"),
getText("ContextMenu_Names450"),
getText("ContextMenu_Names451"),
getText("ContextMenu_Names452"),
getText("ContextMenu_Names453"),
getText("ContextMenu_Names454"),
getText("ContextMenu_Names455"),
getText("ContextMenu_Names456"),
getText("ContextMenu_Names457"),
getText("ContextMenu_Names458"),
getText("ContextMenu_Names459"),
getText("ContextMenu_Names460"),
getText("ContextMenu_Names461"),
getText("ContextMenu_Names462"),
getText("ContextMenu_Names463"),
getText("ContextMenu_Names464"),
getText("ContextMenu_Names465"),
getText("ContextMenu_Names466"),
getText("ContextMenu_Names467"),
getText("ContextMenu_Names468"),
getText("ContextMenu_Names469"),
getText("ContextMenu_Names470"),
getText("ContextMenu_Names471"),
getText("ContextMenu_Names472"),
getText("ContextMenu_Names473"),
getText("ContextMenu_Names474"),
getText("ContextMenu_Names475"),
getText("ContextMenu_Names476"),
getText("ContextMenu_Names477"),
getText("ContextMenu_Names478"),
getText("ContextMenu_Names479"),
getText("ContextMenu_Names480"),
getText("ContextMenu_Names481"),
getText("ContextMenu_Names482"),
getText("ContextMenu_Names483"),
getText("ContextMenu_Names484"),
getText("ContextMenu_Names485"),
getText("ContextMenu_Names486"),
getText("ContextMenu_Names487"),
getText("ContextMenu_Names488"),
getText("ContextMenu_Names489"),
getText("ContextMenu_Names490"),
getText("ContextMenu_Names491"),
getText("ContextMenu_Names492"),
getText("ContextMenu_Names493"),
getText("ContextMenu_Names494"),
getText("ContextMenu_Names495"),
getText("ContextMenu_Names496"),
getText("ContextMenu_Names497"),
getText("ContextMenu_Names498"),
getText("ContextMenu_Names499"),
getText("ContextMenu_Names500"),
};
SurvivorSpeechTable["BoyNames"] = {
getText("ContextMenu_Namb1"),
getText("ContextMenu_Namb2"),
getText("ContextMenu_Namb3"),
getText("ContextMenu_Namb4"),
getText("ContextMenu_Namb5"),
getText("ContextMenu_Namb6"),
getText("ContextMenu_Namb7"),
getText("ContextMenu_Namb8"),
getText("ContextMenu_Namb9"),
getText("ContextMenu_Namb10"),
getText("ContextMenu_Namb11"),
getText("ContextMenu_Namb12"),
getText("ContextMenu_Namb13"),
getText("ContextMenu_Namb14"),
getText("ContextMenu_Namb15"),
getText("ContextMenu_Namb16"),
getText("ContextMenu_Namb17"),
getText("ContextMenu_Namb18"),
getText("ContextMenu_Namb19"),
getText("ContextMenu_Namb20"),
getText("ContextMenu_Namb21"),
getText("ContextMenu_Namb22"),
getText("ContextMenu_Namb23"),
getText("ContextMenu_Namb24"),
getText("ContextMenu_Namb25"),
getText("ContextMenu_Namb26"),
getText("ContextMenu_Namb27"),
getText("ContextMenu_Namb28"),
getText("ContextMenu_Namb29"),
getText("ContextMenu_Namb30"),
getText("ContextMenu_Namb31"),
getText("ContextMenu_Namb32"),
getText("ContextMenu_Namb33"),
getText("ContextMenu_Namb34"),
getText("ContextMenu_Namb35"),
getText("ContextMenu_Namb36"),
getText("ContextMenu_Namb37"),
getText("ContextMenu_Namb38"),
getText("ContextMenu_Namb39"),
getText("ContextMenu_Namb40"),
getText("ContextMenu_Namb41"),
getText("ContextMenu_Namb42"),
getText("ContextMenu_Namb43"),
getText("ContextMenu_Namb44"),
getText("ContextMenu_Namb45"),
getText("ContextMenu_Namb46"),
getText("ContextMenu_Namb47"),
getText("ContextMenu_Namb48"),
getText("ContextMenu_Namb49"),
getText("ContextMenu_Namb50"),
getText("ContextMenu_Namb51"),
getText("ContextMenu_Namb52"),
getText("ContextMenu_Namb53"),
getText("ContextMenu_Namb54"),
getText("ContextMenu_Namb55"),
getText("ContextMenu_Namb56"),
getText("ContextMenu_Namb57"),
getText("ContextMenu_Namb58"),
getText("ContextMenu_Namb59"),
getText("ContextMenu_Namb60"),
getText("ContextMenu_Namb61"),
getText("ContextMenu_Namb62"),
getText("ContextMenu_Namb63"),
getText("ContextMenu_Namb64"),
getText("ContextMenu_Namb65"),
getText("ContextMenu_Namb66"),
getText("ContextMenu_Namb67"),
getText("ContextMenu_Namb68"),
getText("ContextMenu_Namb69"),
getText("ContextMenu_Namb70"),
getText("ContextMenu_Namb71"),
getText("ContextMenu_Namb72"),
getText("ContextMenu_Namb73"),
getText("ContextMenu_Namb74"),
getText("ContextMenu_Namb75"),
getText("ContextMenu_Namb76"),
getText("ContextMenu_Namb77"),
getText("ContextMenu_Namb78"),
getText("ContextMenu_Namb79"),
getText("ContextMenu_Namb80"),
getText("ContextMenu_Namb81"),
getText("ContextMenu_Namb82"),
getText("ContextMenu_Namb83"),
getText("ContextMenu_Namb84"),
getText("ContextMenu_Namb85"),
getText("ContextMenu_Namb86"),
getText("ContextMenu_Namb87"),
getText("ContextMenu_Namb88"),
getText("ContextMenu_Namb89"),
getText("ContextMenu_Namb90"),
getText("ContextMenu_Namb91"),
getText("ContextMenu_Namb92"),
getText("ContextMenu_Namb93"),
getText("ContextMenu_Namb94"),
getText("ContextMenu_Namb95"),
getText("ContextMenu_Namb96"),
getText("ContextMenu_Namb97"),
getText("ContextMenu_Namb98"),
getText("ContextMenu_Namb99"),
getText("ContextMenu_Namb100"),
getText("ContextMenu_Namb101"),
getText("ContextMenu_Namb102"),
getText("ContextMenu_Namb103"),
getText("ContextMenu_Namb104"),
getText("ContextMenu_Namb105"),
getText("ContextMenu_Namb106"),
getText("ContextMenu_Namb107"),
getText("ContextMenu_Namb108"),
getText("ContextMenu_Namb109"),
getText("ContextMenu_Namb110"),
getText("ContextMenu_Namb111"),
getText("ContextMenu_Namb112"),
getText("ContextMenu_Namb113"),
getText("ContextMenu_Namb114"),
getText("ContextMenu_Namb115"),
getText("ContextMenu_Namb116"),
getText("ContextMenu_Namb117"),
getText("ContextMenu_Namb118"),
getText("ContextMenu_Namb119"),
getText("ContextMenu_Namb120"),
getText("ContextMenu_Namb121"),
getText("ContextMenu_Namb122"),
getText("ContextMenu_Namb123"),
getText("ContextMenu_Namb124"),
getText("ContextMenu_Namb125"),
getText("ContextMenu_Namb126"),
getText("ContextMenu_Namb127"),
getText("ContextMenu_Namb128"),
getText("ContextMenu_Namb129"),
getText("ContextMenu_Namb130"),
getText("ContextMenu_Namb131"),
getText("ContextMenu_Namb132"),
getText("ContextMenu_Namb133"),
getText("ContextMenu_Namb134"),
getText("ContextMenu_Namb135"),
getText("ContextMenu_Namb136"),
getText("ContextMenu_Namb137"),
getText("ContextMenu_Namb138"),
getText("ContextMenu_Namb139"),
getText("ContextMenu_Namb140"),
getText("ContextMenu_Namb141"),
getText("ContextMenu_Namb142"),
getText("ContextMenu_Namb143"),
getText("ContextMenu_Namb144"),
getText("ContextMenu_Namb145"),
getText("ContextMenu_Namb146"),
getText("ContextMenu_Namb147"),
getText("ContextMenu_Namb148"),
getText("ContextMenu_Namb149"),
getText("ContextMenu_Namb150"),
getText("ContextMenu_Namb151"),
getText("ContextMenu_Namb152"),
getText("ContextMenu_Namb153"),
getText("ContextMenu_Namb154"),
getText("ContextMenu_Namb155"),
getText("ContextMenu_Namb156"),
getText("ContextMenu_Namb157"),
getText("ContextMenu_Namb158"),
getText("ContextMenu_Namb159"),
getText("ContextMenu_Namb160")};
